//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for contact-details-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contact-details-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personal-title" type="{http://www.ema.eaf/dictionary/}string10" minOccurs="0"/>
 *         &lt;element name="given-name" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="family-name" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="company-name" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="address1" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="address2" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="address3" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="address4" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="city" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="state" type="{http://www.ema.eaf/dictionary/}string100" minOccurs="0"/>
 *         &lt;element name="county" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="post-code" type="{http://www.ema.eaf/dictionary/}string10"/>
 *         &lt;element name="country" type="{http://www.ema.eaf/dictionary/}control-term"/>
 *         &lt;element name="orgID" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="locID" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="loc-modifiedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="org-modifiedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="language" type="{http://www.ema.eaf/dictionary/}string10"/>
 *         &lt;element name="phone" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="email" type="{http://www.ema.eaf/dictionary/}string100" minOccurs="0"/>
 *         &lt;element name="qualification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="residesInEEA" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="attach" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="qualifiedPerson" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states"/>
 *         &lt;element name="admin-manu-address" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="admin-office" type="{http://www.ema.eaf/dictionary/}admin-office"/>
 *         &lt;element name="manu-facility" type="{http://www.ema.eaf/dictionary/}manu-facility" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contact-details-type", propOrder = {
    "personalTitle",
    "givenName",
    "familyName",
    "companyName",
    "address1",
    "address2",
    "address3",
    "address4",
    "city",
    "state",
    "county",
    "postCode",
    "country",
    "orgID",
    "locID",
    "locModifiedDate",
    "orgModifiedDate",
    "language",
    "phone",
    "email",
    "qualification",
    "residesInEEA",
    "attach",
    "qualifiedPerson",
    "memberStates",
    "adminManuAddress",
    "adminOffice",
    "manuFacility"
})
@XmlSeeAlso({
    ContactBloodVaccine.class,
    eu.europa.ema.v1_26.form.ContractStudy.ContractCompany.class,
    MarketingAuthorisationHolder.class,
    PharmacoVigilance.class,
    ContactScientificAdvice.class,
    ContactBatchTestingSite.class
})
public class ContactDetailsType {

    @XmlElement(name = "personal-title")
    protected String personalTitle;
    @XmlElement(name = "given-name", required = true)
    protected String givenName;
    @XmlElement(name = "family-name", required = true)
    protected String familyName;
    @XmlElement(name = "company-name", required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String address1;
    @XmlElement(required = true)
    protected String address2;
    @XmlElement(required = true)
    protected String address3;
    @XmlElement(required = true)
    protected String address4;
    @XmlElement(required = true)
    protected String city;
    protected String state;
    @XmlElement(required = true)
    protected String county;
    @XmlElement(name = "post-code", required = true)
    protected String postCode;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String orgID;
    @XmlElement(required = true)
    protected String locID;
    @XmlElement(name = "loc-modifiedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar locModifiedDate;
    @XmlElement(name = "org-modifiedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orgModifiedDate;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String phone;
    protected String email;
    protected String qualification;
    protected Integer residesInEEA;
    protected int attach;
    protected Integer qualifiedPerson;
    @XmlElement(name = "member-states", required = true)
    protected MemberStates memberStates;
    @XmlElement(name = "admin-manu-address")
    protected int adminManuAddress;
    @XmlElement(name = "admin-office", required = true)
    protected AdminOffice adminOffice;
    @XmlElement(name = "manu-facility", required = true)
    protected List<ManuFacility> manuFacility;

    /**
     * Gets the value of the personalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalTitle() {
        return personalTitle;
    }

    /**
     * Sets the value of the personalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalTitle(String value) {
        this.personalTitle = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the address3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * Sets the value of the address3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress3(String value) {
        this.address3 = value;
    }

    /**
     * Gets the value of the address4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress4() {
        return address4;
    }

    /**
     * Sets the value of the address4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress4(String value) {
        this.address4 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the orgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgID() {
        return orgID;
    }

    /**
     * Sets the value of the orgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgID(String value) {
        this.orgID = value;
    }

    /**
     * Gets the value of the locID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocID() {
        return locID;
    }

    /**
     * Sets the value of the locID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocID(String value) {
        this.locID = value;
    }

    /**
     * Gets the value of the locModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLocModifiedDate() {
        return locModifiedDate;
    }

    /**
     * Sets the value of the locModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLocModifiedDate(XMLGregorianCalendar value) {
        this.locModifiedDate = value;
    }

    /**
     * Gets the value of the orgModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrgModifiedDate() {
        return orgModifiedDate;
    }

    /**
     * Sets the value of the orgModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrgModifiedDate(XMLGregorianCalendar value) {
        this.orgModifiedDate = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the qualification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * Sets the value of the qualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualification(String value) {
        this.qualification = value;
    }

    /**
     * Gets the value of the residesInEEA property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResidesInEEA() {
        return residesInEEA;
    }

    /**
     * Sets the value of the residesInEEA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResidesInEEA(Integer value) {
        this.residesInEEA = value;
    }

    /**
     * Gets the value of the attach property.
     * 
     */
    public int getAttach() {
        return attach;
    }

    /**
     * Sets the value of the attach property.
     * 
     */
    public void setAttach(int value) {
        this.attach = value;
    }

    /**
     * Gets the value of the qualifiedPerson property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQualifiedPerson() {
        return qualifiedPerson;
    }

    /**
     * Sets the value of the qualifiedPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQualifiedPerson(Integer value) {
        this.qualifiedPerson = value;
    }

    /**
     * Gets the value of the memberStates property.
     * 
     * @return
     *     possible object is
     *     {@link MemberStates }
     *     
     */
    public MemberStates getMemberStates() {
        return memberStates;
    }

    /**
     * Sets the value of the memberStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberStates }
     *     
     */
    public void setMemberStates(MemberStates value) {
        this.memberStates = value;
    }

    /**
     * Gets the value of the adminManuAddress property.
     * 
     */
    public int getAdminManuAddress() {
        return adminManuAddress;
    }

    /**
     * Sets the value of the adminManuAddress property.
     * 
     */
    public void setAdminManuAddress(int value) {
        this.adminManuAddress = value;
    }

    /**
     * Gets the value of the adminOffice property.
     * 
     * @return
     *     possible object is
     *     {@link AdminOffice }
     *     
     */
    public AdminOffice getAdminOffice() {
        return adminOffice;
    }

    /**
     * Sets the value of the adminOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminOffice }
     *     
     */
    public void setAdminOffice(AdminOffice value) {
        this.adminOffice = value;
    }

    /**
     * Gets the value of the manuFacility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manuFacility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManuFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManuFacility }
     * 
     * 
     */
    public List<ManuFacility> getManuFacility() {
        if (manuFacility == null) {
            manuFacility = new ArrayList<ManuFacility>();
        }
        return this.manuFacility;
    }

}
