//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contract-study complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contract-study">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="studies" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title-of-study" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="protocol-code" type="{http://www.ema.eaf/dictionary/}string30"/>
 *                   &lt;element name="eudraCT-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contract-company" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.ema.eaf/dictionary/}contact-details-type">
 *                 &lt;sequence>
 *                   &lt;element name="contract-duty-performed" type="{http://www.ema.eaf/dictionary/}string30"/>
 *                   &lt;element name="product_name" type="{http://www.ema.eaf/dictionary/}string250"/>
 *                   &lt;element name="product_country" type="{http://www.ema.eaf/dictionary/}control-term"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contract-study", propOrder = {
    "studies",
    "contractCompany"
})
public class ContractStudy {

    @XmlElement(required = true)
    protected List<ContractStudy.Studies> studies;
    @XmlElement(name = "contract-company", required = true)
    protected List<ContractStudy.ContractCompany> contractCompany;

    /**
     * Gets the value of the studies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContractStudy.Studies }
     * 
     * 
     */
    public List<ContractStudy.Studies> getStudies() {
        if (studies == null) {
            studies = new ArrayList<ContractStudy.Studies>();
        }
        return this.studies;
    }

    /**
     * Gets the value of the contractCompany property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractCompany property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractCompany().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContractStudy.ContractCompany }
     * 
     * 
     */
    public List<ContractStudy.ContractCompany> getContractCompany() {
        if (contractCompany == null) {
            contractCompany = new ArrayList<ContractStudy.ContractCompany>();
        }
        return this.contractCompany;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.ema.eaf/dictionary/}contact-details-type">
     *       &lt;sequence>
     *         &lt;element name="contract-duty-performed" type="{http://www.ema.eaf/dictionary/}string30"/>
     *         &lt;element name="product_name" type="{http://www.ema.eaf/dictionary/}string250"/>
     *         &lt;element name="product_country" type="{http://www.ema.eaf/dictionary/}control-term"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractDutyPerformed",
        "productName",
        "productCountry"
    })
    public static class ContractCompany
        extends ContactDetailsType
    {

        @XmlElement(name = "contract-duty-performed", required = true)
        protected String contractDutyPerformed;
        @XmlElement(name = "product_name", required = true)
        protected String productName;
        @XmlElement(name = "product_country", required = true)
        protected String productCountry;

        /**
         * Gets the value of the contractDutyPerformed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractDutyPerformed() {
            return contractDutyPerformed;
        }

        /**
         * Sets the value of the contractDutyPerformed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractDutyPerformed(String value) {
            this.contractDutyPerformed = value;
        }

        /**
         * Gets the value of the productName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductName() {
            return productName;
        }

        /**
         * Sets the value of the productName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductName(String value) {
            this.productName = value;
        }

        /**
         * Gets the value of the productCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductCountry() {
            return productCountry;
        }

        /**
         * Sets the value of the productCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductCountry(String value) {
            this.productCountry = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title-of-study" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="protocol-code" type="{http://www.ema.eaf/dictionary/}string30"/>
     *         &lt;element name="eudraCT-number" type="{http://www.ema.eaf/dictionary/}string30"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titleOfStudy",
        "protocolCode",
        "eudraCTNumber"
    })
    public static class Studies {

        @XmlElement(name = "title-of-study", required = true)
        protected String titleOfStudy;
        @XmlElement(name = "protocol-code", required = true)
        protected String protocolCode;
        @XmlElement(name = "eudraCT-number", required = true)
        protected String eudraCTNumber;

        /**
         * Gets the value of the titleOfStudy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitleOfStudy() {
            return titleOfStudy;
        }

        /**
         * Sets the value of the titleOfStudy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitleOfStudy(String value) {
            this.titleOfStudy = value;
        }

        /**
         * Gets the value of the protocolCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtocolCode() {
            return protocolCode;
        }

        /**
         * Sets the value of the protocolCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtocolCode(String value) {
            this.protocolCode = value;
        }

        /**
         * Gets the value of the eudraCTNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEudraCTNumber() {
            return eudraCTNumber;
        }

        /**
         * Sets the value of the eudraCTNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEudraCTNumber(String value) {
            this.eudraCTNumber = value;
        }

    }

}
