//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for decentralised-procedure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="decentralised-procedure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ema.eaf/dictionary/}generic-procedure">
 *       &lt;sequence>
 *         &lt;element name="reference-member-state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states"/>
 *         &lt;element name="proposed-agreed-renewal-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="after-initial-procedure" type="{http://www.ema.eaf/dictionary/}radiobutton" minOccurs="0"/>
 *         &lt;element name="member-renewals">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="member-renewal" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states"/>
 *                             &lt;element name="proposed-agreed-renewal-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "decentralised-procedure", propOrder = {
    "referenceMemberState",
    "memberStates",
    "proposedAgreedRenewalDate",
    "afterInitialProcedure",
    "memberRenewals"
})
public class DecentralisedProcedure
    extends GenericProcedure
{

    @XmlElement(name = "reference-member-state", required = true)
    protected String referenceMemberState;
    @XmlElement(name = "member-states", required = true)
    protected MemberStates memberStates;
    @XmlElement(name = "proposed-agreed-renewal-date", required = true)
    protected String proposedAgreedRenewalDate;
    @XmlElement(name = "after-initial-procedure")
    protected BigInteger afterInitialProcedure;
    @XmlElement(name = "member-renewals", required = true)
    protected DecentralisedProcedure.MemberRenewals memberRenewals;

    /**
     * Gets the value of the referenceMemberState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceMemberState() {
        return referenceMemberState;
    }

    /**
     * Sets the value of the referenceMemberState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceMemberState(String value) {
        this.referenceMemberState = value;
    }

    /**
     * Gets the value of the memberStates property.
     * 
     * @return
     *     possible object is
     *     {@link MemberStates }
     *     
     */
    public MemberStates getMemberStates() {
        return memberStates;
    }

    /**
     * Sets the value of the memberStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberStates }
     *     
     */
    public void setMemberStates(MemberStates value) {
        this.memberStates = value;
    }

    /**
     * Gets the value of the proposedAgreedRenewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProposedAgreedRenewalDate() {
        return proposedAgreedRenewalDate;
    }

    /**
     * Sets the value of the proposedAgreedRenewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProposedAgreedRenewalDate(String value) {
        this.proposedAgreedRenewalDate = value;
    }

    /**
     * Gets the value of the afterInitialProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAfterInitialProcedure() {
        return afterInitialProcedure;
    }

    /**
     * Sets the value of the afterInitialProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAfterInitialProcedure(BigInteger value) {
        this.afterInitialProcedure = value;
    }

    /**
     * Gets the value of the memberRenewals property.
     * 
     * @return
     *     possible object is
     *     {@link DecentralisedProcedure.MemberRenewals }
     *     
     */
    public DecentralisedProcedure.MemberRenewals getMemberRenewals() {
        return memberRenewals;
    }

    /**
     * Sets the value of the memberRenewals property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecentralisedProcedure.MemberRenewals }
     *     
     */
    public void setMemberRenewals(DecentralisedProcedure.MemberRenewals value) {
        this.memberRenewals = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="member-renewal" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states"/>
     *                   &lt;element name="proposed-agreed-renewal-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "memberRenewal"
    })
    public static class MemberRenewals {

        @XmlElement(name = "member-renewal", required = true)
        protected List<DecentralisedProcedure.MemberRenewals.MemberRenewal> memberRenewal;

        /**
         * Gets the value of the memberRenewal property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the memberRenewal property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMemberRenewal().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DecentralisedProcedure.MemberRenewals.MemberRenewal }
         * 
         * 
         */
        public List<DecentralisedProcedure.MemberRenewals.MemberRenewal> getMemberRenewal() {
            if (memberRenewal == null) {
                memberRenewal = new ArrayList<DecentralisedProcedure.MemberRenewals.MemberRenewal>();
            }
            return this.memberRenewal;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states"/>
         *         &lt;element name="proposed-agreed-renewal-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "memberStates",
            "proposedAgreedRenewalDate"
        })
        public static class MemberRenewal {

            @XmlElement(name = "member-states", required = true)
            protected MemberStates memberStates;
            @XmlElement(name = "proposed-agreed-renewal-date", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar proposedAgreedRenewalDate;

            /**
             * Gets the value of the memberStates property.
             * 
             * @return
             *     possible object is
             *     {@link MemberStates }
             *     
             */
            public MemberStates getMemberStates() {
                return memberStates;
            }

            /**
             * Sets the value of the memberStates property.
             * 
             * @param value
             *     allowed object is
             *     {@link MemberStates }
             *     
             */
            public void setMemberStates(MemberStates value) {
                this.memberStates = value;
            }

            /**
             * Gets the value of the proposedAgreedRenewalDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getProposedAgreedRenewalDate() {
                return proposedAgreedRenewalDate;
            }

            /**
             * Sets the value of the proposedAgreedRenewalDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setProposedAgreedRenewalDate(XMLGregorianCalendar value) {
                this.proposedAgreedRenewalDate = value;
            }

        }

    }

}
