//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for envelope complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="envelope">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wsurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xsdVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isEditable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="listModTimes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="modTime" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="list-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="mod-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lists">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="countries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="nonEEACountries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="eeaCountries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="euAndFreeTradeCountries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="eeaCountriesExcludingUkNi" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="euAndEftaCountriesExcludingUkNi" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="eeaCountriesAndUkGb" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="pharmaForms" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="routesOfAdmin" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="strengthOperators" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="strengthUnits" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="containers" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="adminDevices" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="closures" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="specPrecaution4Storage" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="mrlSpecies" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="mrlProvision" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="tissueMRL" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="targetSpecies" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="manufacturerControlTests" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="manufacturerFunctions" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="manufacturerSteps" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                   &lt;element name="substanceType" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "envelope", propOrder = {
    "wsurl",
    "formVersion",
    "xsdVersion",
    "formtype",
    "isEditable",
    "listModTimes",
    "lists"
})
public class Envelope {

    @XmlElement(required = true)
    protected String wsurl;
    @XmlElement(required = true)
    protected String formVersion;
    @XmlElement(required = true)
    protected String xsdVersion;
    @XmlElement(required = true)
    protected String formtype;
    protected boolean isEditable;
    @XmlElement(required = true)
    protected Envelope.ListModTimes listModTimes;
    @XmlElement(required = true)
    protected Envelope.Lists lists;

    /**
     * Gets the value of the wsurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsurl() {
        return wsurl;
    }

    /**
     * Sets the value of the wsurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsurl(String value) {
        this.wsurl = value;
    }

    /**
     * Gets the value of the formVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormVersion() {
        return formVersion;
    }

    /**
     * Sets the value of the formVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormVersion(String value) {
        this.formVersion = value;
    }

    /**
     * Gets the value of the xsdVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdVersion() {
        return xsdVersion;
    }

    /**
     * Sets the value of the xsdVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdVersion(String value) {
        this.xsdVersion = value;
    }

    /**
     * Gets the value of the formtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormtype() {
        return formtype;
    }

    /**
     * Sets the value of the formtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormtype(String value) {
        this.formtype = value;
    }

    /**
     * Gets the value of the isEditable property.
     * 
     */
    public boolean isIsEditable() {
        return isEditable;
    }

    /**
     * Sets the value of the isEditable property.
     * 
     */
    public void setIsEditable(boolean value) {
        this.isEditable = value;
    }

    /**
     * Gets the value of the listModTimes property.
     * 
     * @return
     *     possible object is
     *     {@link Envelope.ListModTimes }
     *     
     */
    public Envelope.ListModTimes getListModTimes() {
        return listModTimes;
    }

    /**
     * Sets the value of the listModTimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope.ListModTimes }
     *     
     */
    public void setListModTimes(Envelope.ListModTimes value) {
        this.listModTimes = value;
    }

    /**
     * Gets the value of the lists property.
     * 
     * @return
     *     possible object is
     *     {@link Envelope.Lists }
     *     
     */
    public Envelope.Lists getLists() {
        return lists;
    }

    /**
     * Sets the value of the lists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope.Lists }
     *     
     */
    public void setLists(Envelope.Lists value) {
        this.lists = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="modTime" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="list-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="mod-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "modTime"
    })
    public static class ListModTimes {

        protected List<Envelope.ListModTimes.ModTime> modTime;

        /**
         * Gets the value of the modTime property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the modTime property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModTime().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Envelope.ListModTimes.ModTime }
         * 
         * 
         */
        public List<Envelope.ListModTimes.ModTime> getModTime() {
            if (modTime == null) {
                modTime = new ArrayList<Envelope.ListModTimes.ModTime>();
            }
            return this.modTime;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="list-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="mod-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "listName",
            "modDate"
        })
        public static class ModTime {

            @XmlElement(name = "list-name", required = true)
            protected String listName;
            @XmlElement(name = "mod-date", required = true)
            protected String modDate;

            /**
             * Gets the value of the listName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getListName() {
                return listName;
            }

            /**
             * Sets the value of the listName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setListName(String value) {
                this.listName = value;
            }

            /**
             * Gets the value of the modDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModDate() {
                return modDate;
            }

            /**
             * Sets the value of the modDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModDate(String value) {
                this.modDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="countries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="nonEEACountries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="eeaCountries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="euAndFreeTradeCountries" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="eeaCountriesExcludingUkNi" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="euAndEftaCountriesExcludingUkNi" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="eeaCountriesAndUkGb" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="pharmaForms" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="routesOfAdmin" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="strengthOperators" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="strengthUnits" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="containers" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="adminDevices" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="closures" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="specPrecaution4Storage" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="mrlSpecies" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="mrlProvision" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="tissueMRL" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="targetSpecies" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="manufacturerControlTests" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="manufacturerFunctions" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="manufacturerSteps" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *         &lt;element name="substanceType" type="{http://www.ema.eaf/dictionary/}eutctListType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countries",
        "nonEEACountries",
        "eeaCountries",
        "euAndFreeTradeCountries",
        "eeaCountriesExcludingUkNi",
        "euAndEftaCountriesExcludingUkNi",
        "eeaCountriesAndUkGb",
        "pharmaForms",
        "routesOfAdmin",
        "strengthOperators",
        "strengthUnits",
        "containers",
        "adminDevices",
        "closures",
        "specPrecaution4Storage",
        "mrlSpecies",
        "mrlProvision",
        "tissueMRL",
        "targetSpecies",
        "manufacturerControlTests",
        "manufacturerFunctions",
        "manufacturerSteps",
        "substanceType"
    })
    public static class Lists {

        @XmlElement(required = true)
        protected EutctListType countries;
        @XmlElement(required = true)
        protected EutctListType nonEEACountries;
        @XmlElement(required = true)
        protected EutctListType eeaCountries;
        @XmlElement(required = true)
        protected EutctListType euAndFreeTradeCountries;
        @XmlElement(required = true)
        protected EutctListType eeaCountriesExcludingUkNi;
        @XmlElement(required = true)
        protected EutctListType euAndEftaCountriesExcludingUkNi;
        @XmlElement(required = true)
        protected EutctListType eeaCountriesAndUkGb;
        @XmlElement(required = true)
        protected EutctListType pharmaForms;
        @XmlElement(required = true)
        protected EutctListType routesOfAdmin;
        @XmlElement(required = true)
        protected EutctListType strengthOperators;
        @XmlElement(required = true)
        protected EutctListType strengthUnits;
        @XmlElement(required = true)
        protected EutctListType containers;
        @XmlElement(required = true)
        protected EutctListType adminDevices;
        @XmlElement(required = true)
        protected EutctListType closures;
        @XmlElement(required = true)
        protected EutctListType specPrecaution4Storage;
        @XmlElement(required = true)
        protected EutctListType mrlSpecies;
        @XmlElement(required = true)
        protected EutctListType mrlProvision;
        @XmlElement(required = true)
        protected EutctListType tissueMRL;
        @XmlElement(required = true)
        protected EutctListType targetSpecies;
        @XmlElement(required = true)
        protected EutctListType manufacturerControlTests;
        @XmlElement(required = true)
        protected EutctListType manufacturerFunctions;
        @XmlElement(required = true)
        protected EutctListType manufacturerSteps;
        @XmlElement(required = true)
        protected EutctListType substanceType;

        /**
         * Gets the value of the countries property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getCountries() {
            return countries;
        }

        /**
         * Sets the value of the countries property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setCountries(EutctListType value) {
            this.countries = value;
        }

        /**
         * Gets the value of the nonEEACountries property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getNonEEACountries() {
            return nonEEACountries;
        }

        /**
         * Sets the value of the nonEEACountries property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setNonEEACountries(EutctListType value) {
            this.nonEEACountries = value;
        }

        /**
         * Gets the value of the eeaCountries property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getEeaCountries() {
            return eeaCountries;
        }

        /**
         * Sets the value of the eeaCountries property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setEeaCountries(EutctListType value) {
            this.eeaCountries = value;
        }

        /**
         * Gets the value of the euAndFreeTradeCountries property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getEuAndFreeTradeCountries() {
            return euAndFreeTradeCountries;
        }

        /**
         * Sets the value of the euAndFreeTradeCountries property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setEuAndFreeTradeCountries(EutctListType value) {
            this.euAndFreeTradeCountries = value;
        }

        /**
         * Gets the value of the eeaCountriesExcludingUkNi property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getEeaCountriesExcludingUkNi() {
            return eeaCountriesExcludingUkNi;
        }

        /**
         * Sets the value of the eeaCountriesExcludingUkNi property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setEeaCountriesExcludingUkNi(EutctListType value) {
            this.eeaCountriesExcludingUkNi = value;
        }

        /**
         * Gets the value of the euAndEftaCountriesExcludingUkNi property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getEuAndEftaCountriesExcludingUkNi() {
            return euAndEftaCountriesExcludingUkNi;
        }

        /**
         * Sets the value of the euAndEftaCountriesExcludingUkNi property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setEuAndEftaCountriesExcludingUkNi(EutctListType value) {
            this.euAndEftaCountriesExcludingUkNi = value;
        }

        /**
         * Gets the value of the eeaCountriesAndUkGb property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getEeaCountriesAndUkGb() {
            return eeaCountriesAndUkGb;
        }

        /**
         * Sets the value of the eeaCountriesAndUkGb property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setEeaCountriesAndUkGb(EutctListType value) {
            this.eeaCountriesAndUkGb = value;
        }

        /**
         * Gets the value of the pharmaForms property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getPharmaForms() {
            return pharmaForms;
        }

        /**
         * Sets the value of the pharmaForms property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setPharmaForms(EutctListType value) {
            this.pharmaForms = value;
        }

        /**
         * Gets the value of the routesOfAdmin property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getRoutesOfAdmin() {
            return routesOfAdmin;
        }

        /**
         * Sets the value of the routesOfAdmin property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setRoutesOfAdmin(EutctListType value) {
            this.routesOfAdmin = value;
        }

        /**
         * Gets the value of the strengthOperators property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getStrengthOperators() {
            return strengthOperators;
        }

        /**
         * Sets the value of the strengthOperators property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setStrengthOperators(EutctListType value) {
            this.strengthOperators = value;
        }

        /**
         * Gets the value of the strengthUnits property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getStrengthUnits() {
            return strengthUnits;
        }

        /**
         * Sets the value of the strengthUnits property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setStrengthUnits(EutctListType value) {
            this.strengthUnits = value;
        }

        /**
         * Gets the value of the containers property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getContainers() {
            return containers;
        }

        /**
         * Sets the value of the containers property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setContainers(EutctListType value) {
            this.containers = value;
        }

        /**
         * Gets the value of the adminDevices property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getAdminDevices() {
            return adminDevices;
        }

        /**
         * Sets the value of the adminDevices property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setAdminDevices(EutctListType value) {
            this.adminDevices = value;
        }

        /**
         * Gets the value of the closures property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getClosures() {
            return closures;
        }

        /**
         * Sets the value of the closures property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setClosures(EutctListType value) {
            this.closures = value;
        }

        /**
         * Gets the value of the specPrecaution4Storage property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getSpecPrecaution4Storage() {
            return specPrecaution4Storage;
        }

        /**
         * Sets the value of the specPrecaution4Storage property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setSpecPrecaution4Storage(EutctListType value) {
            this.specPrecaution4Storage = value;
        }

        /**
         * Gets the value of the mrlSpecies property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getMrlSpecies() {
            return mrlSpecies;
        }

        /**
         * Sets the value of the mrlSpecies property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setMrlSpecies(EutctListType value) {
            this.mrlSpecies = value;
        }

        /**
         * Gets the value of the mrlProvision property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getMrlProvision() {
            return mrlProvision;
        }

        /**
         * Sets the value of the mrlProvision property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setMrlProvision(EutctListType value) {
            this.mrlProvision = value;
        }

        /**
         * Gets the value of the tissueMRL property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getTissueMRL() {
            return tissueMRL;
        }

        /**
         * Sets the value of the tissueMRL property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setTissueMRL(EutctListType value) {
            this.tissueMRL = value;
        }

        /**
         * Gets the value of the targetSpecies property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getTargetSpecies() {
            return targetSpecies;
        }

        /**
         * Sets the value of the targetSpecies property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setTargetSpecies(EutctListType value) {
            this.targetSpecies = value;
        }

        /**
         * Gets the value of the manufacturerControlTests property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getManufacturerControlTests() {
            return manufacturerControlTests;
        }

        /**
         * Sets the value of the manufacturerControlTests property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setManufacturerControlTests(EutctListType value) {
            this.manufacturerControlTests = value;
        }

        /**
         * Gets the value of the manufacturerFunctions property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getManufacturerFunctions() {
            return manufacturerFunctions;
        }

        /**
         * Sets the value of the manufacturerFunctions property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setManufacturerFunctions(EutctListType value) {
            this.manufacturerFunctions = value;
        }

        /**
         * Gets the value of the manufacturerSteps property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getManufacturerSteps() {
            return manufacturerSteps;
        }

        /**
         * Sets the value of the manufacturerSteps property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setManufacturerSteps(EutctListType value) {
            this.manufacturerSteps = value;
        }

        /**
         * Gets the value of the substanceType property.
         * 
         * @return
         *     possible object is
         *     {@link EutctListType }
         *     
         */
        public EutctListType getSubstanceType() {
            return substanceType;
        }

        /**
         * Sets the value of the substanceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link EutctListType }
         *     
         */
        public void setSubstanceType(EutctListType value) {
            this.substanceType = value;
        }

    }

}
