//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredient-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingredient-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="low-strength-numerator-value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="low-strength-denominator-value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="high-strength-numerator-value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="high-strength-denominator-value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="strength-denominator-unit" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="strength-numerator-unit" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ingredient-role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quantity-operator" type="{http://www.ema.eaf/dictionary/}control-term" minOccurs="0"/>
 *         &lt;element name="substance" type="{http://www.ema.eaf/dictionary/}substance"/>
 *         &lt;element name="active-substance-form" type="{http://www.ema.eaf/dictionary/}control-term" minOccurs="0"/>
 *         &lt;element name="overage" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="overage-quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="substance" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;element name="overage-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="overage-justification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reference-monograph-standard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ingredient-origin" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="substance-certificate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="reference-number-certificate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attachment" type="{http://www.ema.eaf/dictionary/}attachment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingredient-type", propOrder = {
    "lowStrengthNumeratorValue",
    "lowStrengthDenominatorValue",
    "highStrengthNumeratorValue",
    "highStrengthDenominatorValue",
    "strengthDenominatorUnit",
    "strengthNumeratorUnit",
    "ingredientRole",
    "quantityOperator",
    "substance",
    "activeSubstanceForm",
    "overage",
    "referenceMonographStandard",
    "ingredientOrigin",
    "substanceCertificate",
    "attachment"
})
@XmlSeeAlso({
    StrengthExcipient.class
})
public class IngredientType {

    @XmlElement(name = "low-strength-numerator-value")
    protected Float lowStrengthNumeratorValue;
    @XmlElement(name = "low-strength-denominator-value")
    protected Float lowStrengthDenominatorValue;
    @XmlElement(name = "high-strength-numerator-value")
    protected Float highStrengthNumeratorValue;
    @XmlElement(name = "high-strength-denominator-value")
    protected Float highStrengthDenominatorValue;
    @XmlElement(name = "strength-denominator-unit")
    protected Object strengthDenominatorUnit;
    @XmlElement(name = "strength-numerator-unit")
    protected Object strengthNumeratorUnit;
    @XmlElement(name = "ingredient-role")
    protected String ingredientRole;
    @XmlElement(name = "quantity-operator")
    protected String quantityOperator;
    @XmlElement(required = true)
    protected Substance substance;
    @XmlElement(name = "active-substance-form")
    protected String activeSubstanceForm;
    protected List<IngredientType.Overage> overage;
    @XmlElement(name = "reference-monograph-standard")
    protected String referenceMonographStandard;
    @XmlElement(name = "ingredient-origin")
    protected List<String> ingredientOrigin;
    @XmlElement(name = "substance-certificate", required = true)
    protected IngredientType.SubstanceCertificate substanceCertificate;
    protected List<Attachment> attachment;

    /**
     * Gets the value of the lowStrengthNumeratorValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLowStrengthNumeratorValue() {
        return lowStrengthNumeratorValue;
    }

    /**
     * Sets the value of the lowStrengthNumeratorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLowStrengthNumeratorValue(Float value) {
        this.lowStrengthNumeratorValue = value;
    }

    /**
     * Gets the value of the lowStrengthDenominatorValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLowStrengthDenominatorValue() {
        return lowStrengthDenominatorValue;
    }

    /**
     * Sets the value of the lowStrengthDenominatorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLowStrengthDenominatorValue(Float value) {
        this.lowStrengthDenominatorValue = value;
    }

    /**
     * Gets the value of the highStrengthNumeratorValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHighStrengthNumeratorValue() {
        return highStrengthNumeratorValue;
    }

    /**
     * Sets the value of the highStrengthNumeratorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHighStrengthNumeratorValue(Float value) {
        this.highStrengthNumeratorValue = value;
    }

    /**
     * Gets the value of the highStrengthDenominatorValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHighStrengthDenominatorValue() {
        return highStrengthDenominatorValue;
    }

    /**
     * Sets the value of the highStrengthDenominatorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHighStrengthDenominatorValue(Float value) {
        this.highStrengthDenominatorValue = value;
    }

    /**
     * Gets the value of the strengthDenominatorUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStrengthDenominatorUnit() {
        return strengthDenominatorUnit;
    }

    /**
     * Sets the value of the strengthDenominatorUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStrengthDenominatorUnit(Object value) {
        this.strengthDenominatorUnit = value;
    }

    /**
     * Gets the value of the strengthNumeratorUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStrengthNumeratorUnit() {
        return strengthNumeratorUnit;
    }

    /**
     * Sets the value of the strengthNumeratorUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStrengthNumeratorUnit(Object value) {
        this.strengthNumeratorUnit = value;
    }

    /**
     * Gets the value of the ingredientRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIngredientRole() {
        return ingredientRole;
    }

    /**
     * Sets the value of the ingredientRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIngredientRole(String value) {
        this.ingredientRole = value;
    }

    /**
     * Gets the value of the quantityOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityOperator() {
        return quantityOperator;
    }

    /**
     * Sets the value of the quantityOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityOperator(String value) {
        this.quantityOperator = value;
    }

    /**
     * Gets the value of the substance property.
     * 
     * @return
     *     possible object is
     *     {@link Substance }
     *     
     */
    public Substance getSubstance() {
        return substance;
    }

    /**
     * Sets the value of the substance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Substance }
     *     
     */
    public void setSubstance(Substance value) {
        this.substance = value;
    }

    /**
     * Gets the value of the activeSubstanceForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveSubstanceForm() {
        return activeSubstanceForm;
    }

    /**
     * Sets the value of the activeSubstanceForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveSubstanceForm(String value) {
        this.activeSubstanceForm = value;
    }

    /**
     * Gets the value of the overage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IngredientType.Overage }
     * 
     * 
     */
    public List<IngredientType.Overage> getOverage() {
        if (overage == null) {
            overage = new ArrayList<IngredientType.Overage>();
        }
        return this.overage;
    }

    /**
     * Gets the value of the referenceMonographStandard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceMonographStandard() {
        return referenceMonographStandard;
    }

    /**
     * Sets the value of the referenceMonographStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceMonographStandard(String value) {
        this.referenceMonographStandard = value;
    }

    /**
     * Gets the value of the ingredientOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredientOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredientOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIngredientOrigin() {
        if (ingredientOrigin == null) {
            ingredientOrigin = new ArrayList<String>();
        }
        return this.ingredientOrigin;
    }

    /**
     * Gets the value of the substanceCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link IngredientType.SubstanceCertificate }
     *     
     */
    public IngredientType.SubstanceCertificate getSubstanceCertificate() {
        return substanceCertificate;
    }

    /**
     * Sets the value of the substanceCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IngredientType.SubstanceCertificate }
     *     
     */
    public void setSubstanceCertificate(IngredientType.SubstanceCertificate value) {
        this.substanceCertificate = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attachment }
     * 
     * 
     */
    public List<Attachment> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<Attachment>();
        }
        return this.attachment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="overage-quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="substance" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         &lt;element name="overage-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="overage-justification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "overageQuantity",
        "substance",
        "overageReason",
        "overageJustification"
    })
    public static class Overage {

        @XmlElement(name = "overage-quantity", required = true)
        protected String overageQuantity;
        @XmlElement(required = true)
        protected List<String> substance;
        @XmlElement(name = "overage-reason")
        protected String overageReason;
        @XmlElement(name = "overage-justification")
        protected String overageJustification;

        /**
         * Gets the value of the overageQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOverageQuantity() {
            return overageQuantity;
        }

        /**
         * Sets the value of the overageQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOverageQuantity(String value) {
            this.overageQuantity = value;
        }

        /**
         * Gets the value of the substance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the substance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSubstance() {
            if (substance == null) {
                substance = new ArrayList<String>();
            }
            return this.substance;
        }

        /**
         * Gets the value of the overageReason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOverageReason() {
            return overageReason;
        }

        /**
         * Sets the value of the overageReason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOverageReason(String value) {
            this.overageReason = value;
        }

        /**
         * Gets the value of the overageJustification property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOverageJustification() {
            return overageJustification;
        }

        /**
         * Sets the value of the overageJustification property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOverageJustification(String value) {
            this.overageJustification = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="reference-number-certificate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "referenceNumberCertificate"
    })
    public static class SubstanceCertificate {

        @XmlElement(name = "reference-number-certificate", required = true)
        protected String referenceNumberCertificate;
        @XmlAttribute(name = "type")
        @XmlSchemaType(name = "anySimpleType")
        protected String type;

        /**
         * Gets the value of the referenceNumberCertificate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceNumberCertificate() {
            return referenceNumberCertificate;
        }

        /**
         * Sets the value of the referenceNumberCertificate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceNumberCertificate(String value) {
            this.referenceNumberCertificate = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
