//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for manufacturer-pharmaceutical-product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="manufacturer-pharmaceutical-product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partial-product-desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact-details" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manu-functions" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="manu-function" type="{http://www.ema.eaf/dictionary/}control-term"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attach-annex-5-8" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="site-in-EEA" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="site-out-EEA" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="inside" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="manufacturing-auth-number" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                   &lt;element name="manufacturing-auth-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                   &lt;element name="attach-annex-5-6" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="eudraGMP-certificate-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                   &lt;element name="attach-annex-5-9" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="qualified-person" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="outside" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DUNS-number" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                   &lt;element name="attach-directive-annex-5-6" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="gmp-compliance-eea" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="gmp-compliance-eea-outcome" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *                   &lt;element name="three-year-auth-inspection" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="attach-GMP-certificate" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="eudraGMP-certificate-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                   &lt;element name="gmp-compliance-other" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="gmp-compliance-other-outcome" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *                   &lt;element name="attach-annex-5-9" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "manufacturer-pharmaceutical-product", propOrder = {
    "partialProductDesc",
    "contactDetails",
    "desc",
    "manuFunctions",
    "attachAnnex58",
    "siteInEEA",
    "siteOutEEA",
    "inside",
    "outside"
})
public class ManufacturerPharmaceuticalProduct {

    @XmlElement(name = "partial-product-desc", required = true)
    protected String partialProductDesc;
    @XmlElement(name = "contact-details", required = true)
    protected ContactDetailsType contactDetails;
    @XmlElement(required = true)
    protected String desc;
    @XmlElement(name = "manu-functions", required = true)
    protected List<ManufacturerPharmaceuticalProduct.ManuFunctions> manuFunctions;
    @XmlElement(name = "attach-annex-5-8")
    protected int attachAnnex58;
    @XmlElement(name = "site-in-EEA")
    protected int siteInEEA;
    @XmlElement(name = "site-out-EEA")
    protected int siteOutEEA;
    @XmlElement(required = true)
    protected List<ManufacturerPharmaceuticalProduct.Inside> inside;
    @XmlElement(required = true)
    protected List<ManufacturerPharmaceuticalProduct.Outside> outside;

    /**
     * Gets the value of the partialProductDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialProductDesc() {
        return partialProductDesc;
    }

    /**
     * Sets the value of the partialProductDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialProductDesc(String value) {
        this.partialProductDesc = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetailsType }
     *     
     */
    public ContactDetailsType getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetailsType }
     *     
     */
    public void setContactDetails(ContactDetailsType value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the manuFunctions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manuFunctions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManuFunctions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerPharmaceuticalProduct.ManuFunctions }
     * 
     * 
     */
    public List<ManufacturerPharmaceuticalProduct.ManuFunctions> getManuFunctions() {
        if (manuFunctions == null) {
            manuFunctions = new ArrayList<ManufacturerPharmaceuticalProduct.ManuFunctions>();
        }
        return this.manuFunctions;
    }

    /**
     * Gets the value of the attachAnnex58 property.
     * 
     */
    public int getAttachAnnex58() {
        return attachAnnex58;
    }

    /**
     * Sets the value of the attachAnnex58 property.
     * 
     */
    public void setAttachAnnex58(int value) {
        this.attachAnnex58 = value;
    }

    /**
     * Gets the value of the siteInEEA property.
     * 
     */
    public int getSiteInEEA() {
        return siteInEEA;
    }

    /**
     * Sets the value of the siteInEEA property.
     * 
     */
    public void setSiteInEEA(int value) {
        this.siteInEEA = value;
    }

    /**
     * Gets the value of the siteOutEEA property.
     * 
     */
    public int getSiteOutEEA() {
        return siteOutEEA;
    }

    /**
     * Sets the value of the siteOutEEA property.
     * 
     */
    public void setSiteOutEEA(int value) {
        this.siteOutEEA = value;
    }

    /**
     * Gets the value of the inside property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inside property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInside().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerPharmaceuticalProduct.Inside }
     * 
     * 
     */
    public List<ManufacturerPharmaceuticalProduct.Inside> getInside() {
        if (inside == null) {
            inside = new ArrayList<ManufacturerPharmaceuticalProduct.Inside>();
        }
        return this.inside;
    }

    /**
     * Gets the value of the outside property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outside property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutside().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerPharmaceuticalProduct.Outside }
     * 
     * 
     */
    public List<ManufacturerPharmaceuticalProduct.Outside> getOutside() {
        if (outside == null) {
            outside = new ArrayList<ManufacturerPharmaceuticalProduct.Outside>();
        }
        return this.outside;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="manufacturing-auth-number" type="{http://www.ema.eaf/dictionary/}string100"/>
     *         &lt;element name="manufacturing-auth-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
     *         &lt;element name="attach-annex-5-6" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="eudraGMP-certificate-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
     *         &lt;element name="attach-annex-5-9" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="qualified-person" type="{http://www.ema.eaf/dictionary/}string100"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "manufacturingAuthNumber",
        "manufacturingAuthReference",
        "attachAnnex56",
        "eudraGMPCertificateReference",
        "attachAnnex59",
        "qualifiedPerson"
    })
    public static class Inside {

        @XmlElement(name = "manufacturing-auth-number", required = true)
        protected String manufacturingAuthNumber;
        @XmlElement(name = "manufacturing-auth-reference", required = true)
        protected String manufacturingAuthReference;
        @XmlElement(name = "attach-annex-5-6")
        protected int attachAnnex56;
        @XmlElement(name = "eudraGMP-certificate-reference", required = true)
        protected String eudraGMPCertificateReference;
        @XmlElement(name = "attach-annex-5-9")
        protected int attachAnnex59;
        @XmlElement(name = "qualified-person", required = true)
        protected String qualifiedPerson;

        /**
         * Gets the value of the manufacturingAuthNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManufacturingAuthNumber() {
            return manufacturingAuthNumber;
        }

        /**
         * Sets the value of the manufacturingAuthNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManufacturingAuthNumber(String value) {
            this.manufacturingAuthNumber = value;
        }

        /**
         * Gets the value of the manufacturingAuthReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManufacturingAuthReference() {
            return manufacturingAuthReference;
        }

        /**
         * Sets the value of the manufacturingAuthReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManufacturingAuthReference(String value) {
            this.manufacturingAuthReference = value;
        }

        /**
         * Gets the value of the attachAnnex56 property.
         * 
         */
        public int getAttachAnnex56() {
            return attachAnnex56;
        }

        /**
         * Sets the value of the attachAnnex56 property.
         * 
         */
        public void setAttachAnnex56(int value) {
            this.attachAnnex56 = value;
        }

        /**
         * Gets the value of the eudraGMPCertificateReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEudraGMPCertificateReference() {
            return eudraGMPCertificateReference;
        }

        /**
         * Sets the value of the eudraGMPCertificateReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEudraGMPCertificateReference(String value) {
            this.eudraGMPCertificateReference = value;
        }

        /**
         * Gets the value of the attachAnnex59 property.
         * 
         */
        public int getAttachAnnex59() {
            return attachAnnex59;
        }

        /**
         * Sets the value of the attachAnnex59 property.
         * 
         */
        public void setAttachAnnex59(int value) {
            this.attachAnnex59 = value;
        }

        /**
         * Gets the value of the qualifiedPerson property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQualifiedPerson() {
            return qualifiedPerson;
        }

        /**
         * Sets the value of the qualifiedPerson property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQualifiedPerson(String value) {
            this.qualifiedPerson = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="manu-function" type="{http://www.ema.eaf/dictionary/}control-term"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "manuFunction"
    })
    public static class ManuFunctions {

        @XmlElement(name = "manu-function", required = true)
        protected String manuFunction;

        /**
         * Gets the value of the manuFunction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManuFunction() {
            return manuFunction;
        }

        /**
         * Sets the value of the manuFunction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManuFunction(String value) {
            this.manuFunction = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DUNS-number" type="{http://www.ema.eaf/dictionary/}string100"/>
     *         &lt;element name="attach-directive-annex-5-6" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="gmp-compliance-eea" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="gmp-compliance-eea-outcome" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
     *         &lt;element name="three-year-auth-inspection" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="attach-GMP-certificate" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="eudraGMP-certificate-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
     *         &lt;element name="gmp-compliance-other" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="gmp-compliance-other-outcome" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
     *         &lt;element name="attach-annex-5-9" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dunsNumber",
        "attachDirectiveAnnex56",
        "gmpComplianceEea",
        "gmpComplianceEeaOutcome",
        "threeYearAuthInspection",
        "attachGMPCertificate",
        "eudraGMPCertificateReference",
        "gmpComplianceOther",
        "gmpComplianceOtherOutcome",
        "attachAnnex59"
    })
    public static class Outside {

        @XmlElement(name = "DUNS-number", required = true)
        protected String dunsNumber;
        @XmlElement(name = "attach-directive-annex-5-6")
        protected int attachDirectiveAnnex56;
        @XmlElement(name = "gmp-compliance-eea")
        protected int gmpComplianceEea;
        @XmlElement(name = "gmp-compliance-eea-outcome")
        protected Integer gmpComplianceEeaOutcome;
        @XmlElement(name = "three-year-auth-inspection")
        protected int threeYearAuthInspection;
        @XmlElement(name = "attach-GMP-certificate")
        protected int attachGMPCertificate;
        @XmlElement(name = "eudraGMP-certificate-reference", required = true)
        protected String eudraGMPCertificateReference;
        @XmlElement(name = "gmp-compliance-other")
        protected int gmpComplianceOther;
        @XmlElement(name = "gmp-compliance-other-outcome")
        protected Integer gmpComplianceOtherOutcome;
        @XmlElement(name = "attach-annex-5-9")
        protected int attachAnnex59;

        /**
         * Gets the value of the dunsNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDUNSNumber() {
            return dunsNumber;
        }

        /**
         * Sets the value of the dunsNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDUNSNumber(String value) {
            this.dunsNumber = value;
        }

        /**
         * Gets the value of the attachDirectiveAnnex56 property.
         * 
         */
        public int getAttachDirectiveAnnex56() {
            return attachDirectiveAnnex56;
        }

        /**
         * Sets the value of the attachDirectiveAnnex56 property.
         * 
         */
        public void setAttachDirectiveAnnex56(int value) {
            this.attachDirectiveAnnex56 = value;
        }

        /**
         * Gets the value of the gmpComplianceEea property.
         * 
         */
        public int getGmpComplianceEea() {
            return gmpComplianceEea;
        }

        /**
         * Sets the value of the gmpComplianceEea property.
         * 
         */
        public void setGmpComplianceEea(int value) {
            this.gmpComplianceEea = value;
        }

        /**
         * Gets the value of the gmpComplianceEeaOutcome property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getGmpComplianceEeaOutcome() {
            return gmpComplianceEeaOutcome;
        }

        /**
         * Sets the value of the gmpComplianceEeaOutcome property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setGmpComplianceEeaOutcome(Integer value) {
            this.gmpComplianceEeaOutcome = value;
        }

        /**
         * Gets the value of the threeYearAuthInspection property.
         * 
         */
        public int getThreeYearAuthInspection() {
            return threeYearAuthInspection;
        }

        /**
         * Sets the value of the threeYearAuthInspection property.
         * 
         */
        public void setThreeYearAuthInspection(int value) {
            this.threeYearAuthInspection = value;
        }

        /**
         * Gets the value of the attachGMPCertificate property.
         * 
         */
        public int getAttachGMPCertificate() {
            return attachGMPCertificate;
        }

        /**
         * Sets the value of the attachGMPCertificate property.
         * 
         */
        public void setAttachGMPCertificate(int value) {
            this.attachGMPCertificate = value;
        }

        /**
         * Gets the value of the eudraGMPCertificateReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEudraGMPCertificateReference() {
            return eudraGMPCertificateReference;
        }

        /**
         * Sets the value of the eudraGMPCertificateReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEudraGMPCertificateReference(String value) {
            this.eudraGMPCertificateReference = value;
        }

        /**
         * Gets the value of the gmpComplianceOther property.
         * 
         */
        public int getGmpComplianceOther() {
            return gmpComplianceOther;
        }

        /**
         * Sets the value of the gmpComplianceOther property.
         * 
         */
        public void setGmpComplianceOther(int value) {
            this.gmpComplianceOther = value;
        }

        /**
         * Gets the value of the gmpComplianceOtherOutcome property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getGmpComplianceOtherOutcome() {
            return gmpComplianceOtherOutcome;
        }

        /**
         * Sets the value of the gmpComplianceOtherOutcome property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setGmpComplianceOtherOutcome(Integer value) {
            this.gmpComplianceOtherOutcome = value;
        }

        /**
         * Gets the value of the attachAnnex59 property.
         * 
         */
        public int getAttachAnnex59() {
            return attachAnnex59;
        }

        /**
         * Sets the value of the attachAnnex59 property.
         * 
         */
        public void setAttachAnnex59(int value) {
            this.attachAnnex59 = value;
        }

    }

}
