//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for manufacturer-batch-release complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="manufacturer-batch-release">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contact-details" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
 *         &lt;element name="manufacturing-auth-number" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="attach-annex5-6" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="eudraGMP-auth-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="selecteudraGMP-auth-reference" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="attach-gmp-certificate" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="eudraGMP-certificate-reference" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="selectedeudraGMP-certificate-reference" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="package-responsible-manufacturer" type="{http://www.ema.eaf/dictionary/}string250"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "manufacturer-batch-release", propOrder = {
    "contactDetails",
    "manufacturingAuthNumber",
    "attachAnnex56",
    "eudraGMPAuthReference",
    "selecteudraGMPAuthReference",
    "attachGmpCertificate",
    "eudraGMPCertificateReference",
    "selectedeudraGMPCertificateReference",
    "packageResponsibleManufacturer"
})
public class ManufacturerBatchRelease {

    @XmlElement(name = "contact-details", required = true)
    protected ContactDetailsType contactDetails;
    @XmlElement(name = "manufacturing-auth-number", required = true)
    protected String manufacturingAuthNumber;
    @XmlElement(name = "attach-annex5-6")
    protected int attachAnnex56;
    @XmlElement(name = "eudraGMP-auth-reference", required = true)
    protected String eudraGMPAuthReference;
    @XmlElement(name = "selecteudraGMP-auth-reference")
    protected Object selecteudraGMPAuthReference;
    @XmlElement(name = "attach-gmp-certificate")
    protected int attachGmpCertificate;
    @XmlElement(name = "eudraGMP-certificate-reference", required = true)
    protected String eudraGMPCertificateReference;
    @XmlElement(name = "selectedeudraGMP-certificate-reference")
    protected Object selectedeudraGMPCertificateReference;
    @XmlElement(name = "package-responsible-manufacturer", required = true)
    protected String packageResponsibleManufacturer;

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetailsType }
     *     
     */
    public ContactDetailsType getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetailsType }
     *     
     */
    public void setContactDetails(ContactDetailsType value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the manufacturingAuthNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturingAuthNumber() {
        return manufacturingAuthNumber;
    }

    /**
     * Sets the value of the manufacturingAuthNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturingAuthNumber(String value) {
        this.manufacturingAuthNumber = value;
    }

    /**
     * Gets the value of the attachAnnex56 property.
     * 
     */
    public int getAttachAnnex56() {
        return attachAnnex56;
    }

    /**
     * Sets the value of the attachAnnex56 property.
     * 
     */
    public void setAttachAnnex56(int value) {
        this.attachAnnex56 = value;
    }

    /**
     * Gets the value of the eudraGMPAuthReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEudraGMPAuthReference() {
        return eudraGMPAuthReference;
    }

    /**
     * Sets the value of the eudraGMPAuthReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEudraGMPAuthReference(String value) {
        this.eudraGMPAuthReference = value;
    }

    /**
     * Gets the value of the selecteudraGMPAuthReference property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSelecteudraGMPAuthReference() {
        return selecteudraGMPAuthReference;
    }

    /**
     * Sets the value of the selecteudraGMPAuthReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSelecteudraGMPAuthReference(Object value) {
        this.selecteudraGMPAuthReference = value;
    }

    /**
     * Gets the value of the attachGmpCertificate property.
     * 
     */
    public int getAttachGmpCertificate() {
        return attachGmpCertificate;
    }

    /**
     * Sets the value of the attachGmpCertificate property.
     * 
     */
    public void setAttachGmpCertificate(int value) {
        this.attachGmpCertificate = value;
    }

    /**
     * Gets the value of the eudraGMPCertificateReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEudraGMPCertificateReference() {
        return eudraGMPCertificateReference;
    }

    /**
     * Sets the value of the eudraGMPCertificateReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEudraGMPCertificateReference(String value) {
        this.eudraGMPCertificateReference = value;
    }

    /**
     * Gets the value of the selectedeudraGMPCertificateReference property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSelectedeudraGMPCertificateReference() {
        return selectedeudraGMPCertificateReference;
    }

    /**
     * Sets the value of the selectedeudraGMPCertificateReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSelectedeudraGMPCertificateReference(Object value) {
        this.selectedeudraGMPCertificateReference = value;
    }

    /**
     * Gets the value of the packageResponsibleManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageResponsibleManufacturer() {
        return packageResponsibleManufacturer;
    }

    /**
     * Sets the value of the packageResponsibleManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageResponsibleManufacturer(String value) {
        this.packageResponsibleManufacturer = value;
    }

}
