//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for manufacturer-active-substance-vet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="manufacturer-active-substance-vet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="active-substances" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="active-substance" type="{http://www.ema.eaf/dictionary/}ingredient" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contact-details" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
 *         &lt;element name="function-description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manu-steps" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="manu-step" type="{http://www.ema.eaf/dictionary/}control-term"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="flow_chart" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="qualified-person-declaration" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="inspected_gmp_compliance" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="competent-authority" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="gmp_cert" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="gmpc" type="{http://www.ema.eaf/dictionary/}gmpc"/>
 *         &lt;element name="gmp-compliance-other" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="summary-information" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="ph-eur-cert-suitability" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="provide-copy" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="qualification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="attach" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="active-substance-master-file" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="access-community-member-state" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="ph-eur-cert">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="asmf">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet"/>
 *                   &lt;element name="contact-details" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vamf" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="is-vamf-issued" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ptmf" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="is-ptmf-issued" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet"/>
 *                   &lt;element name="provide-copy" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "manufacturer-active-substance-vet", propOrder = {
    "activeSubstances",
    "contactDetails",
    "functionDescription",
    "manuSteps",
    "flowChart",
    "qualifiedPersonDeclaration",
    "inspectedGmpCompliance",
    "competentAuthority",
    "gmpCert",
    "gmpc",
    "gmpComplianceOther",
    "summaryInformation",
    "phEurCertSuitability",
    "provideCopy",
    "qualification",
    "attach",
    "activeSubstanceMasterFile",
    "accessCommunityMemberState",
    "phEurCert",
    "asmf",
    "vamf",
    "ptmf"
})
public class ManufacturerActiveSubstanceVet {

    @XmlElement(name = "active-substances", required = true)
    protected List<ManufacturerActiveSubstanceVet.ActiveSubstances> activeSubstances;
    @XmlElement(name = "contact-details", required = true)
    protected ContactDetailsType contactDetails;
    @XmlElement(name = "function-description", required = true)
    protected String functionDescription;
    @XmlElement(name = "manu-steps", required = true)
    protected List<ManufacturerActiveSubstanceVet.ManuSteps> manuSteps;
    @XmlElement(name = "flow_chart")
    protected int flowChart;
    @XmlElement(name = "qualified-person-declaration")
    protected int qualifiedPersonDeclaration;
    @XmlElement(name = "inspected_gmp_compliance")
    protected int inspectedGmpCompliance;
    @XmlElement(name = "competent-authority")
    protected int competentAuthority;
    @XmlElement(name = "gmp_cert")
    protected int gmpCert;
    @XmlElement(required = true)
    protected Gmpc gmpc;
    @XmlElement(name = "gmp-compliance-other")
    protected int gmpComplianceOther;
    @XmlElement(name = "summary-information")
    protected int summaryInformation;
    @XmlElement(name = "ph-eur-cert-suitability")
    protected int phEurCertSuitability;
    @XmlElement(name = "provide-copy")
    protected int provideCopy;
    protected String qualification;
    protected Integer attach;
    @XmlElement(name = "active-substance-master-file")
    protected int activeSubstanceMasterFile;
    @XmlElement(name = "access-community-member-state")
    protected int accessCommunityMemberState;
    @XmlElement(name = "ph-eur-cert", required = true)
    protected ManufacturerActiveSubstanceVet.PhEurCert phEurCert;
    @XmlElement(required = true)
    protected ManufacturerActiveSubstanceVet.Asmf asmf;
    @XmlElement(required = true)
    protected List<ManufacturerActiveSubstanceVet.Vamf> vamf;
    @XmlElement(required = true)
    protected List<ManufacturerActiveSubstanceVet.Ptmf> ptmf;

    /**
     * Gets the value of the activeSubstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activeSubstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActiveSubstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerActiveSubstanceVet.ActiveSubstances }
     * 
     * 
     */
    public List<ManufacturerActiveSubstanceVet.ActiveSubstances> getActiveSubstances() {
        if (activeSubstances == null) {
            activeSubstances = new ArrayList<ManufacturerActiveSubstanceVet.ActiveSubstances>();
        }
        return this.activeSubstances;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetailsType }
     *     
     */
    public ContactDetailsType getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetailsType }
     *     
     */
    public void setContactDetails(ContactDetailsType value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the functionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionDescription() {
        return functionDescription;
    }

    /**
     * Sets the value of the functionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionDescription(String value) {
        this.functionDescription = value;
    }

    /**
     * Gets the value of the manuSteps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manuSteps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManuSteps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerActiveSubstanceVet.ManuSteps }
     * 
     * 
     */
    public List<ManufacturerActiveSubstanceVet.ManuSteps> getManuSteps() {
        if (manuSteps == null) {
            manuSteps = new ArrayList<ManufacturerActiveSubstanceVet.ManuSteps>();
        }
        return this.manuSteps;
    }

    /**
     * Gets the value of the flowChart property.
     * 
     */
    public int getFlowChart() {
        return flowChart;
    }

    /**
     * Sets the value of the flowChart property.
     * 
     */
    public void setFlowChart(int value) {
        this.flowChart = value;
    }

    /**
     * Gets the value of the qualifiedPersonDeclaration property.
     * 
     */
    public int getQualifiedPersonDeclaration() {
        return qualifiedPersonDeclaration;
    }

    /**
     * Sets the value of the qualifiedPersonDeclaration property.
     * 
     */
    public void setQualifiedPersonDeclaration(int value) {
        this.qualifiedPersonDeclaration = value;
    }

    /**
     * Gets the value of the inspectedGmpCompliance property.
     * 
     */
    public int getInspectedGmpCompliance() {
        return inspectedGmpCompliance;
    }

    /**
     * Sets the value of the inspectedGmpCompliance property.
     * 
     */
    public void setInspectedGmpCompliance(int value) {
        this.inspectedGmpCompliance = value;
    }

    /**
     * Gets the value of the competentAuthority property.
     * 
     */
    public int getCompetentAuthority() {
        return competentAuthority;
    }

    /**
     * Sets the value of the competentAuthority property.
     * 
     */
    public void setCompetentAuthority(int value) {
        this.competentAuthority = value;
    }

    /**
     * Gets the value of the gmpCert property.
     * 
     */
    public int getGmpCert() {
        return gmpCert;
    }

    /**
     * Sets the value of the gmpCert property.
     * 
     */
    public void setGmpCert(int value) {
        this.gmpCert = value;
    }

    /**
     * Gets the value of the gmpc property.
     * 
     * @return
     *     possible object is
     *     {@link Gmpc }
     *     
     */
    public Gmpc getGmpc() {
        return gmpc;
    }

    /**
     * Sets the value of the gmpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gmpc }
     *     
     */
    public void setGmpc(Gmpc value) {
        this.gmpc = value;
    }

    /**
     * Gets the value of the gmpComplianceOther property.
     * 
     */
    public int getGmpComplianceOther() {
        return gmpComplianceOther;
    }

    /**
     * Sets the value of the gmpComplianceOther property.
     * 
     */
    public void setGmpComplianceOther(int value) {
        this.gmpComplianceOther = value;
    }

    /**
     * Gets the value of the summaryInformation property.
     * 
     */
    public int getSummaryInformation() {
        return summaryInformation;
    }

    /**
     * Sets the value of the summaryInformation property.
     * 
     */
    public void setSummaryInformation(int value) {
        this.summaryInformation = value;
    }

    /**
     * Gets the value of the phEurCertSuitability property.
     * 
     */
    public int getPhEurCertSuitability() {
        return phEurCertSuitability;
    }

    /**
     * Sets the value of the phEurCertSuitability property.
     * 
     */
    public void setPhEurCertSuitability(int value) {
        this.phEurCertSuitability = value;
    }

    /**
     * Gets the value of the provideCopy property.
     * 
     */
    public int getProvideCopy() {
        return provideCopy;
    }

    /**
     * Sets the value of the provideCopy property.
     * 
     */
    public void setProvideCopy(int value) {
        this.provideCopy = value;
    }

    /**
     * Gets the value of the qualification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * Sets the value of the qualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualification(String value) {
        this.qualification = value;
    }

    /**
     * Gets the value of the attach property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttach() {
        return attach;
    }

    /**
     * Sets the value of the attach property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttach(Integer value) {
        this.attach = value;
    }

    /**
     * Gets the value of the activeSubstanceMasterFile property.
     * 
     */
    public int getActiveSubstanceMasterFile() {
        return activeSubstanceMasterFile;
    }

    /**
     * Sets the value of the activeSubstanceMasterFile property.
     * 
     */
    public void setActiveSubstanceMasterFile(int value) {
        this.activeSubstanceMasterFile = value;
    }

    /**
     * Gets the value of the accessCommunityMemberState property.
     * 
     */
    public int getAccessCommunityMemberState() {
        return accessCommunityMemberState;
    }

    /**
     * Sets the value of the accessCommunityMemberState property.
     * 
     */
    public void setAccessCommunityMemberState(int value) {
        this.accessCommunityMemberState = value;
    }

    /**
     * Gets the value of the phEurCert property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturerActiveSubstanceVet.PhEurCert }
     *     
     */
    public ManufacturerActiveSubstanceVet.PhEurCert getPhEurCert() {
        return phEurCert;
    }

    /**
     * Sets the value of the phEurCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturerActiveSubstanceVet.PhEurCert }
     *     
     */
    public void setPhEurCert(ManufacturerActiveSubstanceVet.PhEurCert value) {
        this.phEurCert = value;
    }

    /**
     * Gets the value of the asmf property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturerActiveSubstanceVet.Asmf }
     *     
     */
    public ManufacturerActiveSubstanceVet.Asmf getAsmf() {
        return asmf;
    }

    /**
     * Sets the value of the asmf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturerActiveSubstanceVet.Asmf }
     *     
     */
    public void setAsmf(ManufacturerActiveSubstanceVet.Asmf value) {
        this.asmf = value;
    }

    /**
     * Gets the value of the vamf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vamf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVamf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerActiveSubstanceVet.Vamf }
     * 
     * 
     */
    public List<ManufacturerActiveSubstanceVet.Vamf> getVamf() {
        if (vamf == null) {
            vamf = new ArrayList<ManufacturerActiveSubstanceVet.Vamf>();
        }
        return this.vamf;
    }

    /**
     * Gets the value of the ptmf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptmf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtmf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManufacturerActiveSubstanceVet.Ptmf }
     * 
     * 
     */
    public List<ManufacturerActiveSubstanceVet.Ptmf> getPtmf() {
        if (ptmf == null) {
            ptmf = new ArrayList<ManufacturerActiveSubstanceVet.Ptmf>();
        }
        return this.ptmf;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="active-substance" type="{http://www.ema.eaf/dictionary/}ingredient" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "activeSubstance"
    })
    public static class ActiveSubstances {

        @XmlElement(name = "active-substance", required = true)
        protected List<Ingredient> activeSubstance;

        /**
         * Gets the value of the activeSubstance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the activeSubstance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActiveSubstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ingredient }
         * 
         * 
         */
        public List<Ingredient> getActiveSubstance() {
            if (activeSubstance == null) {
                activeSubstance = new ArrayList<Ingredient>();
            }
            return this.activeSubstance;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet"/>
     *         &lt;element name="contact-details" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "substanceCertificate",
        "contactDetails"
    })
    public static class Asmf {

        @XmlElement(name = "substance-certificate", required = true)
        protected SubstanceCertificateVet substanceCertificate;
        @XmlElement(name = "contact-details", required = true)
        protected ContactDetailsType contactDetails;

        /**
         * Gets the value of the substanceCertificate property.
         * 
         * @return
         *     possible object is
         *     {@link SubstanceCertificateVet }
         *     
         */
        public SubstanceCertificateVet getSubstanceCertificate() {
            return substanceCertificate;
        }

        /**
         * Sets the value of the substanceCertificate property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubstanceCertificateVet }
         *     
         */
        public void setSubstanceCertificate(SubstanceCertificateVet value) {
            this.substanceCertificate = value;
        }

        /**
         * Gets the value of the contactDetails property.
         * 
         * @return
         *     possible object is
         *     {@link ContactDetailsType }
         *     
         */
        public ContactDetailsType getContactDetails() {
            return contactDetails;
        }

        /**
         * Sets the value of the contactDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContactDetailsType }
         *     
         */
        public void setContactDetails(ContactDetailsType value) {
            this.contactDetails = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="manu-step" type="{http://www.ema.eaf/dictionary/}control-term"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "manuStep"
    })
    public static class ManuSteps {

        @XmlElement(name = "manu-step", required = true)
        protected String manuStep;

        /**
         * Gets the value of the manuStep property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManuStep() {
            return manuStep;
        }

        /**
         * Sets the value of the manuStep property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManuStep(String value) {
            this.manuStep = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "substanceCertificate"
    })
    public static class PhEurCert {

        @XmlElement(name = "substance-certificate", required = true)
        protected List<SubstanceCertificateVet> substanceCertificate;

        /**
         * Gets the value of the substanceCertificate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the substanceCertificate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubstanceCertificate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SubstanceCertificateVet }
         * 
         * 
         */
        public List<SubstanceCertificateVet> getSubstanceCertificate() {
            if (substanceCertificate == null) {
                substanceCertificate = new ArrayList<SubstanceCertificateVet>();
            }
            return this.substanceCertificate;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="is-ptmf-issued" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet"/>
     *         &lt;element name="provide-copy" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isPtmfIssued",
        "substanceCertificate",
        "provideCopy"
    })
    public static class Ptmf {

        @XmlElement(name = "is-ptmf-issued", required = true)
        protected Object isPtmfIssued;
        @XmlElement(name = "substance-certificate", required = true)
        protected SubstanceCertificateVet substanceCertificate;
        @XmlElement(name = "provide-copy")
        protected Integer provideCopy;

        /**
         * Gets the value of the isPtmfIssued property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIsPtmfIssued() {
            return isPtmfIssued;
        }

        /**
         * Sets the value of the isPtmfIssued property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIsPtmfIssued(Object value) {
            this.isPtmfIssued = value;
        }

        /**
         * Gets the value of the substanceCertificate property.
         * 
         * @return
         *     possible object is
         *     {@link SubstanceCertificateVet }
         *     
         */
        public SubstanceCertificateVet getSubstanceCertificate() {
            return substanceCertificate;
        }

        /**
         * Sets the value of the substanceCertificate property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubstanceCertificateVet }
         *     
         */
        public void setSubstanceCertificate(SubstanceCertificateVet value) {
            this.substanceCertificate = value;
        }

        /**
         * Gets the value of the provideCopy property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getProvideCopy() {
            return provideCopy;
        }

        /**
         * Sets the value of the provideCopy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setProvideCopy(Integer value) {
            this.provideCopy = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="is-vamf-issued" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="substance-certificate" type="{http://www.ema.eaf/dictionary/}substance-certificate-vet"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isVamfIssued",
        "substanceCertificate"
    })
    public static class Vamf {

        @XmlElement(name = "is-vamf-issued", required = true)
        protected Object isVamfIssued;
        @XmlElement(name = "substance-certificate", required = true)
        protected SubstanceCertificateVet substanceCertificate;

        /**
         * Gets the value of the isVamfIssued property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIsVamfIssued() {
            return isVamfIssued;
        }

        /**
         * Sets the value of the isVamfIssued property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIsVamfIssued(Object value) {
            this.isVamfIssued = value;
        }

        /**
         * Gets the value of the substanceCertificate property.
         * 
         * @return
         *     possible object is
         *     {@link SubstanceCertificateVet }
         *     
         */
        public SubstanceCertificateVet getSubstanceCertificate() {
            return substanceCertificate;
        }

        /**
         * Sets the value of the substanceCertificate property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubstanceCertificateVet }
         *     
         */
        public void setSubstanceCertificate(SubstanceCertificateVet value) {
            this.substanceCertificate = value;
        }

    }

}
