//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for marketing-authorisation-holder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="marketing-authorisation-holder">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ema.eaf/dictionary/}contact-details-type">
 *       &lt;sequence>
 *         &lt;element name="sme-status" type="{http://www.ema.eaf/dictionary/}sme-status"/>
 *         &lt;element name="Proof-of-payment" type="{http://www.ema.eaf/dictionary/}Proof-of-payment"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marketing-authorisation-holder", propOrder = {
    "smeStatus",
    "proofOfPayment"
})
public class MarketingAuthorisationHolder
    extends ContactDetailsType
{

    @XmlElement(name = "sme-status", required = true)
    protected SmeStatus smeStatus;
    @XmlElement(name = "Proof-of-payment", required = true)
    protected ProofOfPayment proofOfPayment;

    /**
     * Gets the value of the smeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SmeStatus }
     *     
     */
    public SmeStatus getSmeStatus() {
        return smeStatus;
    }

    /**
     * Sets the value of the smeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmeStatus }
     *     
     */
    public void setSmeStatus(SmeStatus value) {
        this.smeStatus = value;
    }

    /**
     * Gets the value of the proofOfPayment property.
     * 
     * @return
     *     possible object is
     *     {@link ProofOfPayment }
     *     
     */
    public ProofOfPayment getProofOfPayment() {
        return proofOfPayment;
    }

    /**
     * Sets the value of the proofOfPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProofOfPayment }
     *     
     */
    public void setProofOfPayment(ProofOfPayment value) {
        this.proofOfPayment = value;
    }

}
