//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for mark-auth-detail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mark-auth-detail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="date-of-auth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="invented-name" type="{http://www.ema.eaf/dictionary/}string250"/>
 *         &lt;element name="auth-name" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="date-refusal" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="date-withdrawal" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="date-suspension" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="date-submission" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="reason" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="auth-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="trade-name" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="attach" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="procedure-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="reason-refusal" type="{http://www.ema.eaf/dictionary/}string250"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mark-auth-detail", propOrder = {
    "country",
    "dateOfAuth",
    "inventedName",
    "authName",
    "dateRefusal",
    "dateWithdrawal",
    "dateSuspension",
    "dateSubmission",
    "reason",
    "authNumber",
    "tradeName",
    "attach",
    "procedureNumber",
    "reasonRefusal"
})
public class MarkAuthDetail {

    @XmlElement(required = true)
    protected String country;
    @XmlElement(name = "date-of-auth", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfAuth;
    @XmlElement(name = "invented-name", required = true)
    protected String inventedName;
    @XmlElement(name = "auth-name", required = true)
    protected String authName;
    @XmlElement(name = "date-refusal", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRefusal;
    @XmlElement(name = "date-withdrawal", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateWithdrawal;
    @XmlElement(name = "date-suspension", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateSuspension;
    @XmlElement(name = "date-submission", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateSubmission;
    @XmlElement(required = true)
    protected String reason;
    @XmlElement(name = "auth-number", required = true)
    protected String authNumber;
    @XmlElement(name = "trade-name", required = true)
    protected String tradeName;
    protected Integer attach;
    @XmlElement(name = "procedure-number", required = true)
    protected String procedureNumber;
    @XmlElement(name = "reason-refusal", required = true)
    protected String reasonRefusal;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the dateOfAuth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfAuth() {
        return dateOfAuth;
    }

    /**
     * Sets the value of the dateOfAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfAuth(XMLGregorianCalendar value) {
        this.dateOfAuth = value;
    }

    /**
     * Gets the value of the inventedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventedName() {
        return inventedName;
    }

    /**
     * Sets the value of the inventedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventedName(String value) {
        this.inventedName = value;
    }

    /**
     * Gets the value of the authName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * Sets the value of the authName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthName(String value) {
        this.authName = value;
    }

    /**
     * Gets the value of the dateRefusal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateRefusal() {
        return dateRefusal;
    }

    /**
     * Sets the value of the dateRefusal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateRefusal(XMLGregorianCalendar value) {
        this.dateRefusal = value;
    }

    /**
     * Gets the value of the dateWithdrawal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateWithdrawal() {
        return dateWithdrawal;
    }

    /**
     * Sets the value of the dateWithdrawal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateWithdrawal(XMLGregorianCalendar value) {
        this.dateWithdrawal = value;
    }

    /**
     * Gets the value of the dateSuspension property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSuspension() {
        return dateSuspension;
    }

    /**
     * Sets the value of the dateSuspension property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSuspension(XMLGregorianCalendar value) {
        this.dateSuspension = value;
    }

    /**
     * Gets the value of the dateSubmission property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSubmission() {
        return dateSubmission;
    }

    /**
     * Sets the value of the dateSubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSubmission(XMLGregorianCalendar value) {
        this.dateSubmission = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the authNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthNumber() {
        return authNumber;
    }

    /**
     * Sets the value of the authNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthNumber(String value) {
        this.authNumber = value;
    }

    /**
     * Gets the value of the tradeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * Sets the value of the tradeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeName(String value) {
        this.tradeName = value;
    }

    /**
     * Gets the value of the attach property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAttach() {
        return attach;
    }

    /**
     * Sets the value of the attach property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAttach(Integer value) {
        this.attach = value;
    }

    /**
     * Gets the value of the procedureNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureNumber() {
        return procedureNumber;
    }

    /**
     * Sets the value of the procedureNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureNumber(String value) {
        this.procedureNumber = value;
    }

    /**
     * Gets the value of the reasonRefusal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonRefusal() {
        return reasonRefusal;
    }

    /**
     * Sets the value of the reasonRefusal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonRefusal(String value) {
        this.reasonRefusal = value;
    }

}
