//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mark-auth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mark-auth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selected" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="mark-auth-detail" type="{http://www.ema.eaf/dictionary/}mark-auth-detail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mark-auth", propOrder = {
    "selected",
    "markAuthDetail"
})
public class MarkAuth {

    protected int selected;
    @XmlElement(name = "mark-auth-detail")
    protected List<MarkAuthDetail> markAuthDetail;

    /**
     * Gets the value of the selected property.
     * 
     */
    public int getSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     * 
     */
    public void setSelected(int value) {
        this.selected = value;
    }

    /**
     * Gets the value of the markAuthDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markAuthDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkAuthDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarkAuthDetail }
     * 
     * 
     */
    public List<MarkAuthDetail> getMarkAuthDetail() {
        if (markAuthDetail == null) {
            markAuthDetail = new ArrayList<MarkAuthDetail>();
        }
        return this.markAuthDetail;
    }

}
