//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for mp-authorisation-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mp-authorisation-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authorisation-numbers" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="authorisation-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mrp-variation-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authorisation-holder" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="authorisation-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authorisation-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiry-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="mrp-dcp-procedure-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="is_marketed" type="{http://www.ema.eaf/dictionary/}yes-no" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mp-authorisation-type", propOrder = {
    "authorisationNumbers",
    "mrpVariationNumber",
    "authorisationHolder",
    "authorisationDate",
    "country",
    "authorisationStatus",
    "expiryDate",
    "mrpDcpProcedureNumber"
})
public class MpAuthorisationType {

    @XmlElement(name = "authorisation-numbers", required = true)
    protected List<MpAuthorisationType.AuthorisationNumbers> authorisationNumbers;
    @XmlElement(name = "mrp-variation-number", required = true)
    protected String mrpVariationNumber;
    @XmlElement(name = "authorisation-holder", required = true)
    protected String authorisationHolder;
    @XmlElement(name = "authorisation-date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar authorisationDate;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(name = "authorisation-status", required = true)
    protected String authorisationStatus;
    @XmlElement(name = "expiry-date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "mrp-dcp-procedure-number", required = true)
    protected String mrpDcpProcedureNumber;
    @XmlAttribute(name = "is_marketed")
    protected Integer isMarketed;

    /**
     * Gets the value of the authorisationNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorisationNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorisationNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MpAuthorisationType.AuthorisationNumbers }
     * 
     * 
     */
    public List<MpAuthorisationType.AuthorisationNumbers> getAuthorisationNumbers() {
        if (authorisationNumbers == null) {
            authorisationNumbers = new ArrayList<MpAuthorisationType.AuthorisationNumbers>();
        }
        return this.authorisationNumbers;
    }

    /**
     * Gets the value of the mrpVariationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrpVariationNumber() {
        return mrpVariationNumber;
    }

    /**
     * Sets the value of the mrpVariationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrpVariationNumber(String value) {
        this.mrpVariationNumber = value;
    }

    /**
     * Gets the value of the authorisationHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorisationHolder() {
        return authorisationHolder;
    }

    /**
     * Sets the value of the authorisationHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorisationHolder(String value) {
        this.authorisationHolder = value;
    }

    /**
     * Gets the value of the authorisationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAuthorisationDate() {
        return authorisationDate;
    }

    /**
     * Sets the value of the authorisationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAuthorisationDate(XMLGregorianCalendar value) {
        this.authorisationDate = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the authorisationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorisationStatus() {
        return authorisationStatus;
    }

    /**
     * Sets the value of the authorisationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorisationStatus(String value) {
        this.authorisationStatus = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the mrpDcpProcedureNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrpDcpProcedureNumber() {
        return mrpDcpProcedureNumber;
    }

    /**
     * Sets the value of the mrpDcpProcedureNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrpDcpProcedureNumber(String value) {
        this.mrpDcpProcedureNumber = value;
    }

    /**
     * Gets the value of the isMarketed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIsMarketed() {
        return isMarketed;
    }

    /**
     * Sets the value of the isMarketed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIsMarketed(Integer value) {
        this.isMarketed = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="authorisation-number" type="{http://www.ema.eaf/dictionary/}string30"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authorisationNumber"
    })
    public static class AuthorisationNumbers {

        @XmlElement(name = "authorisation-number", required = true)
        protected String authorisationNumber;

        /**
         * Gets the value of the authorisationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorisationNumber() {
            return authorisationNumber;
        }

        /**
         * Sets the value of the authorisationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorisationNumber(String value) {
            this.authorisationNumber = value;
        }

    }

}
