//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pharmaco-vigilance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pharmaco-vigilance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ema.eaf/dictionary/}contact-details-type">
 *       &lt;sequence>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="art57-database-box" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pharmaco-vigilance", propOrder = {
    "number",
    "art57DatabaseBox"
})
public class PharmacoVigilance
    extends ContactDetailsType
{

    @XmlElement(required = true)
    protected String number;
    @XmlElement(name = "art57-database-box")
    protected int art57DatabaseBox;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the art57DatabaseBox property.
     * 
     */
    public int getArt57DatabaseBox() {
        return art57DatabaseBox;
    }

    /**
     * Sets the value of the art57DatabaseBox property.
     * 
     */
    public void setArt57DatabaseBox(int value) {
        this.art57DatabaseBox = value;
    }

}
