//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Proof-of-payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Proof-of-payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payment" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fees-paid" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                   &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
 *                   &lt;element name="billing-details" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
 *                             &lt;element name="VAT-number" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                             &lt;element name="Purchase-order-number" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                             &lt;element name="contact-details-type" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
 *                             &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Proof-of-payment", propOrder = {
    "payment"
})
@XmlSeeAlso({
    eu.europa.ema.v1_26.form.Signatory.Payment.class
})
public class ProofOfPayment {

    @XmlElement(required = true)
    protected List<ProofOfPayment.Payment> payment;

    /**
     * Gets the value of the payment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProofOfPayment.Payment }
     * 
     * 
     */
    public List<ProofOfPayment.Payment> getPayment() {
        if (payment == null) {
            payment = new ArrayList<ProofOfPayment.Payment>();
        }
        return this.payment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fees-paid" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *         &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
     *         &lt;element name="billing-details" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
     *                   &lt;element name="VAT-number" type="{http://www.ema.eaf/dictionary/}string100"/>
     *                   &lt;element name="Purchase-order-number" type="{http://www.ema.eaf/dictionary/}string100"/>
     *                   &lt;element name="contact-details-type" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
     *                   &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feesPaid",
        "memberStates",
        "billingDetails"
    })
    public static class Payment {

        @XmlElement(name = "fees-paid")
        protected int feesPaid;
        @XmlElement(name = "member-states", required = true)
        protected List<MemberStates> memberStates;
        @XmlElement(name = "billing-details", required = true)
        protected List<ProofOfPayment.Payment.BillingDetails> billingDetails;

        /**
         * Gets the value of the feesPaid property.
         * 
         */
        public int getFeesPaid() {
            return feesPaid;
        }

        /**
         * Sets the value of the feesPaid property.
         * 
         */
        public void setFeesPaid(int value) {
            this.feesPaid = value;
        }

        /**
         * Gets the value of the memberStates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the memberStates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMemberStates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MemberStates }
         * 
         * 
         */
        public List<MemberStates> getMemberStates() {
            if (memberStates == null) {
                memberStates = new ArrayList<MemberStates>();
            }
            return this.memberStates;
        }

        /**
         * Gets the value of the billingDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the billingDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBillingDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProofOfPayment.Payment.BillingDetails }
         * 
         * 
         */
        public List<ProofOfPayment.Payment.BillingDetails> getBillingDetails() {
            if (billingDetails == null) {
                billingDetails = new ArrayList<ProofOfPayment.Payment.BillingDetails>();
            }
            return this.billingDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
         *         &lt;element name="VAT-number" type="{http://www.ema.eaf/dictionary/}string100"/>
         *         &lt;element name="Purchase-order-number" type="{http://www.ema.eaf/dictionary/}string100"/>
         *         &lt;element name="contact-details-type" type="{http://www.ema.eaf/dictionary/}contact-details-type"/>
         *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "memberStates",
            "vatNumber",
            "purchaseOrderNumber",
            "contactDetailsType",
            "reason"
        })
        public static class BillingDetails {

            @XmlElement(name = "member-states", required = true)
            protected List<MemberStates> memberStates;
            @XmlElement(name = "VAT-number", required = true)
            protected String vatNumber;
            @XmlElement(name = "Purchase-order-number", required = true)
            protected String purchaseOrderNumber;
            @XmlElement(name = "contact-details-type", required = true)
            protected ContactDetailsType contactDetailsType;
            @XmlElement(required = true)
            protected String reason;

            /**
             * Gets the value of the memberStates property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the memberStates property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMemberStates().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MemberStates }
             * 
             * 
             */
            public List<MemberStates> getMemberStates() {
                if (memberStates == null) {
                    memberStates = new ArrayList<MemberStates>();
                }
                return this.memberStates;
            }

            /**
             * Gets the value of the vatNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVATNumber() {
                return vatNumber;
            }

            /**
             * Sets the value of the vatNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVATNumber(String value) {
                this.vatNumber = value;
            }

            /**
             * Gets the value of the purchaseOrderNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPurchaseOrderNumber() {
                return purchaseOrderNumber;
            }

            /**
             * Sets the value of the purchaseOrderNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPurchaseOrderNumber(String value) {
                this.purchaseOrderNumber = value;
            }

            /**
             * Gets the value of the contactDetailsType property.
             * 
             * @return
             *     possible object is
             *     {@link ContactDetailsType }
             *     
             */
            public ContactDetailsType getContactDetailsType() {
                return contactDetailsType;
            }

            /**
             * Sets the value of the contactDetailsType property.
             * 
             * @param value
             *     allowed object is
             *     {@link ContactDetailsType }
             *     
             */
            public void setContactDetailsType(ContactDetailsType value) {
                this.contactDetailsType = value;
            }

            /**
             * Gets the value of the reason property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReason() {
                return reason;
            }

            /**
             * Sets the value of the reason property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReason(String value) {
                this.reason = value;
            }

        }

    }

}
