//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for role complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="role">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="party-identification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="party-identification-type" type="{http://www.ema.eaf/dictionary/}CTL"/>
 *                   &lt;element name="identification-number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="party-relationship" type="{http://www.ema.eaf/dictionary/}CTL" minOccurs="0"/>
 *         &lt;element name="business-category" type="{http://www.ema.eaf/dictionary/}CTL" minOccurs="0"/>
 *         &lt;element name="party-type" type="{http://www.ema.eaf/dictionary/}CTL" minOccurs="0"/>
 *         &lt;element name="personal-title" type="{http://www.ema.eaf/dictionary/}string10" minOccurs="0"/>
 *         &lt;element name="job-title" type="{http://www.ema.eaf/dictionary/}string50" minOccurs="0"/>
 *         &lt;element name="given-name" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="middle-name" type="{http://www.ema.eaf/dictionary/}string50" minOccurs="0"/>
 *         &lt;element name="family-name" type="{http://www.ema.eaf/dictionary/}string50"/>
 *         &lt;element name="initials" type="{http://www.ema.eaf/dictionary/}string10" minOccurs="0"/>
 *         &lt;element name="qualifications" type="{http://www.ema.eaf/dictionary/}CTL" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.ema.eaf/dictionary/}CTL" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.ema.eaf/dictionary/}string100"/>
 *         &lt;element name="company-description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact-details" type="{http://www.ema.eaf/dictionary/}contact-details-type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "role", propOrder = {
    "partyIdentification",
    "partyRelationship",
    "businessCategory",
    "partyType",
    "personalTitle",
    "jobTitle",
    "givenName",
    "middleName",
    "familyName",
    "initials",
    "qualifications",
    "gender",
    "name",
    "companyDescription",
    "contactDetails"
})
public class Role {

    @XmlElement(name = "party-identification")
    protected List<Role.PartyIdentification> partyIdentification;
    @XmlElement(name = "party-relationship")
    protected CTL partyRelationship;
    @XmlElement(name = "business-category")
    protected CTL businessCategory;
    @XmlElement(name = "party-type")
    protected CTL partyType;
    @XmlElement(name = "personal-title")
    protected String personalTitle;
    @XmlElement(name = "job-title")
    protected String jobTitle;
    @XmlElement(name = "given-name", required = true)
    protected String givenName;
    @XmlElement(name = "middle-name")
    protected String middleName;
    @XmlElement(name = "family-name", required = true)
    protected String familyName;
    protected String initials;
    protected CTL qualifications;
    protected CTL gender;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "company-description", required = true)
    protected String companyDescription;
    @XmlElement(name = "contact-details")
    protected ContactDetailsType contactDetails;

    /**
     * Gets the value of the partyIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Role.PartyIdentification }
     * 
     * 
     */
    public List<Role.PartyIdentification> getPartyIdentification() {
        if (partyIdentification == null) {
            partyIdentification = new ArrayList<Role.PartyIdentification>();
        }
        return this.partyIdentification;
    }

    /**
     * Gets the value of the partyRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link CTL }
     *     
     */
    public CTL getPartyRelationship() {
        return partyRelationship;
    }

    /**
     * Sets the value of the partyRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTL }
     *     
     */
    public void setPartyRelationship(CTL value) {
        this.partyRelationship = value;
    }

    /**
     * Gets the value of the businessCategory property.
     * 
     * @return
     *     possible object is
     *     {@link CTL }
     *     
     */
    public CTL getBusinessCategory() {
        return businessCategory;
    }

    /**
     * Sets the value of the businessCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTL }
     *     
     */
    public void setBusinessCategory(CTL value) {
        this.businessCategory = value;
    }

    /**
     * Gets the value of the partyType property.
     * 
     * @return
     *     possible object is
     *     {@link CTL }
     *     
     */
    public CTL getPartyType() {
        return partyType;
    }

    /**
     * Sets the value of the partyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTL }
     *     
     */
    public void setPartyType(CTL value) {
        this.partyType = value;
    }

    /**
     * Gets the value of the personalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalTitle() {
        return personalTitle;
    }

    /**
     * Sets the value of the personalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalTitle(String value) {
        this.personalTitle = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the initials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitials() {
        return initials;
    }

    /**
     * Sets the value of the initials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitials(String value) {
        this.initials = value;
    }

    /**
     * Gets the value of the qualifications property.
     * 
     * @return
     *     possible object is
     *     {@link CTL }
     *     
     */
    public CTL getQualifications() {
        return qualifications;
    }

    /**
     * Sets the value of the qualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTL }
     *     
     */
    public void setQualifications(CTL value) {
        this.qualifications = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link CTL }
     *     
     */
    public CTL getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTL }
     *     
     */
    public void setGender(CTL value) {
        this.gender = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the companyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyDescription() {
        return companyDescription;
    }

    /**
     * Sets the value of the companyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyDescription(String value) {
        this.companyDescription = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetailsType }
     *     
     */
    public ContactDetailsType getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetailsType }
     *     
     */
    public void setContactDetails(ContactDetailsType value) {
        this.contactDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="party-identification-type" type="{http://www.ema.eaf/dictionary/}CTL"/>
     *         &lt;element name="identification-number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partyIdentificationType",
        "identificationNumber"
    })
    public static class PartyIdentification {

        @XmlElement(name = "party-identification-type", required = true)
        protected CTL partyIdentificationType;
        @XmlElement(name = "identification-number", required = true)
        protected Object identificationNumber;

        /**
         * Gets the value of the partyIdentificationType property.
         * 
         * @return
         *     possible object is
         *     {@link CTL }
         *     
         */
        public CTL getPartyIdentificationType() {
            return partyIdentificationType;
        }

        /**
         * Sets the value of the partyIdentificationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTL }
         *     
         */
        public void setPartyIdentificationType(CTL value) {
            this.partyIdentificationType = value;
        }

        /**
         * Gets the value of the identificationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIdentificationNumber() {
            return identificationNumber;
        }

        /**
         * Sets the value of the identificationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIdentificationNumber(Object value) {
            this.identificationNumber = value;
        }

    }

}
