//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scientific-advice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scientific-advice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scientific-advice-chmp" type="{http://www.ema.eaf/dictionary/}sci-advice-details-type"/>
 *         &lt;element name="scientific-advice-member-state">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.ema.eaf/dictionary/}sci-advice-details-type">
 *                 &lt;sequence>
 *                   &lt;element name="attach-copy" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scientific-advice", propOrder = {
    "scientificAdviceChmp",
    "scientificAdviceMemberState"
})
public class ScientificAdvice {

    @XmlElement(name = "scientific-advice-chmp", required = true)
    protected SciAdviceDetailsType scientificAdviceChmp;
    @XmlElement(name = "scientific-advice-member-state", required = true)
    protected ScientificAdvice.ScientificAdviceMemberState scientificAdviceMemberState;

    /**
     * Gets the value of the scientificAdviceChmp property.
     * 
     * @return
     *     possible object is
     *     {@link SciAdviceDetailsType }
     *     
     */
    public SciAdviceDetailsType getScientificAdviceChmp() {
        return scientificAdviceChmp;
    }

    /**
     * Sets the value of the scientificAdviceChmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SciAdviceDetailsType }
     *     
     */
    public void setScientificAdviceChmp(SciAdviceDetailsType value) {
        this.scientificAdviceChmp = value;
    }

    /**
     * Gets the value of the scientificAdviceMemberState property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificAdvice.ScientificAdviceMemberState }
     *     
     */
    public ScientificAdvice.ScientificAdviceMemberState getScientificAdviceMemberState() {
        return scientificAdviceMemberState;
    }

    /**
     * Sets the value of the scientificAdviceMemberState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificAdvice.ScientificAdviceMemberState }
     *     
     */
    public void setScientificAdviceMemberState(ScientificAdvice.ScientificAdviceMemberState value) {
        this.scientificAdviceMemberState = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.ema.eaf/dictionary/}sci-advice-details-type">
     *       &lt;sequence>
     *         &lt;element name="attach-copy" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attachCopy"
    })
    public static class ScientificAdviceMemberState
        extends SciAdviceDetailsType
    {

        @XmlElement(name = "attach-copy")
        protected int attachCopy;

        /**
         * Gets the value of the attachCopy property.
         * 
         */
        public int getAttachCopy() {
            return attachCopy;
        }

        /**
         * Sets the value of the attachCopy property.
         * 
         */
        public void setAttachCopy(int value) {
            this.attachCopy = value;
        }

    }

}
