//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for signatory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="signatory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payment" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.ema.eaf/dictionary/}Proof-of-payment">
 *                 &lt;sequence>
 *                   &lt;element name="payment-selection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fee-category-details" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
 *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="main-Signatory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="role" type="{http://www.ema.eaf/dictionary/}role"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dec-signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="signOnBehalf" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="additional-Signatory" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="role" type="{http://www.ema.eaf/dictionary/}role"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dec-signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signatory", propOrder = {
    "payment",
    "mainSignatory",
    "additionalSignatory"
})
public class Signatory {

    @XmlElement(required = true)
    protected List<Signatory.Payment> payment;
    @XmlElement(name = "main-Signatory", required = true)
    protected Signatory.MainSignatory mainSignatory;
    @XmlElement(name = "additional-Signatory")
    protected List<Signatory.AdditionalSignatory> additionalSignatory;

    /**
     * Gets the value of the payment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Signatory.Payment }
     * 
     * 
     */
    public List<Signatory.Payment> getPayment() {
        if (payment == null) {
            payment = new ArrayList<Signatory.Payment>();
        }
        return this.payment;
    }

    /**
     * Gets the value of the mainSignatory property.
     * 
     * @return
     *     possible object is
     *     {@link Signatory.MainSignatory }
     *     
     */
    public Signatory.MainSignatory getMainSignatory() {
        return mainSignatory;
    }

    /**
     * Sets the value of the mainSignatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Signatory.MainSignatory }
     *     
     */
    public void setMainSignatory(Signatory.MainSignatory value) {
        this.mainSignatory = value;
    }

    /**
     * Gets the value of the additionalSignatory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalSignatory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalSignatory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Signatory.AdditionalSignatory }
     * 
     * 
     */
    public List<Signatory.AdditionalSignatory> getAdditionalSignatory() {
        if (additionalSignatory == null) {
            additionalSignatory = new ArrayList<Signatory.AdditionalSignatory>();
        }
        return this.additionalSignatory;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="role" type="{http://www.ema.eaf/dictionary/}role"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="dec-signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "role",
        "date",
        "decSignature"
    })
    public static class AdditionalSignatory {

        @XmlElement(required = true)
        protected Role role;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "dec-signature", required = true)
        protected String decSignature;

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link Role }
         *     
         */
        public Role getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link Role }
         *     
         */
        public void setRole(Role value) {
            this.role = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the decSignature property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecSignature() {
            return decSignature;
        }

        /**
         * Sets the value of the decSignature property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecSignature(String value) {
            this.decSignature = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="role" type="{http://www.ema.eaf/dictionary/}role"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="dec-signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="signOnBehalf" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "role",
        "date",
        "decSignature",
        "signOnBehalf"
    })
    public static class MainSignatory {

        @XmlElement(required = true)
        protected Role role;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "dec-signature", required = true)
        protected String decSignature;
        protected int signOnBehalf;

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link Role }
         *     
         */
        public Role getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link Role }
         *     
         */
        public void setRole(Role value) {
            this.role = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the decSignature property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecSignature() {
            return decSignature;
        }

        /**
         * Sets the value of the decSignature property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecSignature(String value) {
            this.decSignature = value;
        }

        /**
         * Gets the value of the signOnBehalf property.
         * 
         */
        public int getSignOnBehalf() {
            return signOnBehalf;
        }

        /**
         * Sets the value of the signOnBehalf property.
         * 
         */
        public void setSignOnBehalf(int value) {
            this.signOnBehalf = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.ema.eaf/dictionary/}Proof-of-payment">
     *       &lt;sequence>
     *         &lt;element name="payment-selection" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fee-category-details" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
     *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentSelection",
        "feeCategoryDetails"
    })
    public static class Payment
        extends ProofOfPayment
    {

        @XmlElement(name = "payment-selection", required = true)
        protected String paymentSelection;
        @XmlElement(name = "fee-category-details", required = true)
        protected List<Signatory.Payment.FeeCategoryDetails> feeCategoryDetails;

        /**
         * Gets the value of the paymentSelection property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentSelection() {
            return paymentSelection;
        }

        /**
         * Sets the value of the paymentSelection property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentSelection(String value) {
            this.paymentSelection = value;
        }

        /**
         * Gets the value of the feeCategoryDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feeCategoryDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeeCategoryDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Signatory.Payment.FeeCategoryDetails }
         * 
         * 
         */
        public List<Signatory.Payment.FeeCategoryDetails> getFeeCategoryDetails() {
            if (feeCategoryDetails == null) {
                feeCategoryDetails = new ArrayList<Signatory.Payment.FeeCategoryDetails>();
            }
            return this.feeCategoryDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="member-states" type="{http://www.ema.eaf/dictionary/}member-states" maxOccurs="unbounded"/>
         *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "memberStates",
            "category"
        })
        public static class FeeCategoryDetails {

            @XmlElement(name = "member-states", required = true)
            protected List<MemberStates> memberStates;
            @XmlElement(required = true)
            protected String category;

            /**
             * Gets the value of the memberStates property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the memberStates property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMemberStates().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MemberStates }
             * 
             * 
             */
            public List<MemberStates> getMemberStates() {
                if (memberStates == null) {
                    memberStates = new ArrayList<MemberStates>();
                }
                return this.memberStates;
            }

            /**
             * Gets the value of the category property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategory(String value) {
                this.category = value;
            }

        }

    }

}
