//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sme-status complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sme-status">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="annex5-3" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="assigned" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="emea-sme-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="date-of-expiry" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="annex5-21" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="annex5-7" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sme-status", propOrder = {
    "annex53",
    "assigned",
    "emeaSmeNumber",
    "dateOfExpiry",
    "annex521",
    "annex57"
})
public class SmeStatus {

    @XmlElement(name = "annex5-3")
    protected int annex53;
    protected int assigned;
    @XmlElement(name = "emea-sme-number", required = true)
    protected String emeaSmeNumber;
    @XmlElement(name = "date-of-expiry", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfExpiry;
    @XmlElement(name = "annex5-21")
    protected int annex521;
    @XmlElement(name = "annex5-7")
    protected int annex57;

    /**
     * Gets the value of the annex53 property.
     * 
     */
    public int getAnnex53() {
        return annex53;
    }

    /**
     * Sets the value of the annex53 property.
     * 
     */
    public void setAnnex53(int value) {
        this.annex53 = value;
    }

    /**
     * Gets the value of the assigned property.
     * 
     */
    public int getAssigned() {
        return assigned;
    }

    /**
     * Sets the value of the assigned property.
     * 
     */
    public void setAssigned(int value) {
        this.assigned = value;
    }

    /**
     * Gets the value of the emeaSmeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmeaSmeNumber() {
        return emeaSmeNumber;
    }

    /**
     * Sets the value of the emeaSmeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmeaSmeNumber(String value) {
        this.emeaSmeNumber = value;
    }

    /**
     * Gets the value of the dateOfExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfExpiry() {
        return dateOfExpiry;
    }

    /**
     * Sets the value of the dateOfExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfExpiry(XMLGregorianCalendar value) {
        this.dateOfExpiry = value;
    }

    /**
     * Gets the value of the annex521 property.
     * 
     */
    public int getAnnex521() {
        return annex521;
    }

    /**
     * Sets the value of the annex521 property.
     * 
     */
    public void setAnnex521(int value) {
        this.annex521 = value;
    }

    /**
     * Gets the value of the annex57 property.
     * 
     */
    public int getAnnex57() {
        return annex57;
    }

    /**
     * Sets the value of the annex57 property.
     * 
     */
    public void setAnnex57(int value) {
        this.annex57 = value;
    }

}
