//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for strength-excipient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="strength-excipient">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ema.eaf/dictionary/}ingredient-type">
 *       &lt;sequence>
 *         &lt;element name="excipient" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "strength-excipient", propOrder = {
    "excipient"
})
public class StrengthExcipient
    extends IngredientType
{

    @XmlElement(required = true)
    protected Object excipient;

    /**
     * Gets the value of the excipient property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExcipient() {
        return excipient;
    }

    /**
     * Sets the value of the excipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setExcipient(Object value) {
        this.excipient = value;
    }

}
