//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for substance-certificate-vet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="substance-certificate-vet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="active-substances">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="active-substance" type="{http://www.ema.eaf/dictionary/}ingredient" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ingredient-role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reference-number-certificate" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="National-ASMF-reference-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="Applicant-part-version-number" type="{http://www.ema.eaf/dictionary/}string30"/>
 *         &lt;element name="date-submission" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="date-last-update" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="cep-confirmation" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificate-holder">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                   &lt;element name="manufacturer-name" type="{http://www.ema.eaf/dictionary/}string100"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "substance-certificate-vet", propOrder = {
    "activeSubstances",
    "ingredientRole",
    "referenceNumberCertificate",
    "nationalASMFReferenceNumber",
    "applicantPartVersionNumber",
    "dateSubmission",
    "dateLastUpdate",
    "cepConfirmation",
    "country",
    "certificateHolder"
})
public class SubstanceCertificateVet {

    @XmlElement(name = "active-substances", required = true)
    protected SubstanceCertificateVet.ActiveSubstances activeSubstances;
    @XmlElement(name = "ingredient-role")
    protected String ingredientRole;
    @XmlElement(name = "reference-number-certificate", required = true)
    protected String referenceNumberCertificate;
    @XmlElement(name = "National-ASMF-reference-number", required = true)
    protected String nationalASMFReferenceNumber;
    @XmlElement(name = "Applicant-part-version-number", required = true)
    protected String applicantPartVersionNumber;
    @XmlElement(name = "date-submission")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateSubmission;
    @XmlElement(name = "date-last-update")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateLastUpdate;
    @XmlElement(name = "cep-confirmation")
    protected int cepConfirmation;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(name = "certificate-holder", required = true)
    protected SubstanceCertificateVet.CertificateHolder certificateHolder;
    @XmlAttribute(name = "type")
    @XmlSchemaType(name = "anySimpleType")
    protected String type;

    /**
     * Gets the value of the activeSubstances property.
     * 
     * @return
     *     possible object is
     *     {@link SubstanceCertificateVet.ActiveSubstances }
     *     
     */
    public SubstanceCertificateVet.ActiveSubstances getActiveSubstances() {
        return activeSubstances;
    }

    /**
     * Sets the value of the activeSubstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstanceCertificateVet.ActiveSubstances }
     *     
     */
    public void setActiveSubstances(SubstanceCertificateVet.ActiveSubstances value) {
        this.activeSubstances = value;
    }

    /**
     * Gets the value of the ingredientRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIngredientRole() {
        return ingredientRole;
    }

    /**
     * Sets the value of the ingredientRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIngredientRole(String value) {
        this.ingredientRole = value;
    }

    /**
     * Gets the value of the referenceNumberCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumberCertificate() {
        return referenceNumberCertificate;
    }

    /**
     * Sets the value of the referenceNumberCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumberCertificate(String value) {
        this.referenceNumberCertificate = value;
    }

    /**
     * Gets the value of the nationalASMFReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalASMFReferenceNumber() {
        return nationalASMFReferenceNumber;
    }

    /**
     * Sets the value of the nationalASMFReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalASMFReferenceNumber(String value) {
        this.nationalASMFReferenceNumber = value;
    }

    /**
     * Gets the value of the applicantPartVersionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantPartVersionNumber() {
        return applicantPartVersionNumber;
    }

    /**
     * Sets the value of the applicantPartVersionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantPartVersionNumber(String value) {
        this.applicantPartVersionNumber = value;
    }

    /**
     * Gets the value of the dateSubmission property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSubmission() {
        return dateSubmission;
    }

    /**
     * Sets the value of the dateSubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSubmission(XMLGregorianCalendar value) {
        this.dateSubmission = value;
    }

    /**
     * Gets the value of the dateLastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLastUpdate() {
        return dateLastUpdate;
    }

    /**
     * Sets the value of the dateLastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLastUpdate(XMLGregorianCalendar value) {
        this.dateLastUpdate = value;
    }

    /**
     * Gets the value of the cepConfirmation property.
     * 
     */
    public int getCepConfirmation() {
        return cepConfirmation;
    }

    /**
     * Sets the value of the cepConfirmation property.
     * 
     */
    public void setCepConfirmation(int value) {
        this.cepConfirmation = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the certificateHolder property.
     * 
     * @return
     *     possible object is
     *     {@link SubstanceCertificateVet.CertificateHolder }
     *     
     */
    public SubstanceCertificateVet.CertificateHolder getCertificateHolder() {
        return certificateHolder;
    }

    /**
     * Sets the value of the certificateHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstanceCertificateVet.CertificateHolder }
     *     
     */
    public void setCertificateHolder(SubstanceCertificateVet.CertificateHolder value) {
        this.certificateHolder = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="active-substance" type="{http://www.ema.eaf/dictionary/}ingredient" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "activeSubstance"
    })
    public static class ActiveSubstances {

        @XmlElement(name = "active-substance", required = true)
        protected List<Ingredient> activeSubstance;

        /**
         * Gets the value of the activeSubstance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the activeSubstance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActiveSubstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ingredient }
         * 
         * 
         */
        public List<Ingredient> getActiveSubstance() {
            if (activeSubstance == null) {
                activeSubstance = new ArrayList<Ingredient>();
            }
            return this.activeSubstance;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.ema.eaf/dictionary/}string100"/>
     *         &lt;element name="manufacturer-name" type="{http://www.ema.eaf/dictionary/}string100"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "manufacturerName"
    })
    public static class CertificateHolder {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(name = "manufacturer-name", required = true)
        protected String manufacturerName;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the manufacturerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManufacturerName() {
            return manufacturerName;
        }

        /**
         * Sets the value of the manufacturerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManufacturerName(String value) {
            this.manufacturerName = value;
        }

    }

}
