//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.09 at 12:11:17 PM EEST 
//


package eu.europa.ema.v1_26.form;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for variationItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variationItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selected" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="typeIA" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="typeIAIN" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="typeIB" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="typeIBun" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="typeII" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="typeIIart29" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="typeVet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alternative-timetable">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="alternative-timetable-rb" type="{http://www.ema.eaf/dictionary/}radiobutton"/>
 *                   &lt;element name="confirm-alternative-timetable-cb" type="{http://www.ema.eaf/dictionary/}yes-no"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="article5" type="{http://www.ema.eaf/dictionary/}yes-no" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://www.ema.eaf/dictionary/}string100" minOccurs="0"/>
 *         &lt;element name="conditions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="condition" type="{http://www.ema.eaf/dictionary/}condition" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="documentations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="documentation" type="{http://www.ema.eaf/dictionary/}documentation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="typeIAapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="typeIAINapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="typeIBapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="typeIBunapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="typeIIapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="typeIIart29applicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="article5applicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="conditionsapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="documentationsapplicable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variationItem", propOrder = {
    "selected",
    "title",
    "identifier",
    "shortName",
    "typeIA",
    "typeIAIN",
    "typeIB",
    "typeIBun",
    "typeII",
    "typeIIart29",
    "typeVet",
    "alternativeTimetable",
    "article5",
    "date",
    "comment",
    "conditions",
    "documentations",
    "typeIAapplicable",
    "typeIAINapplicable",
    "typeIBapplicable",
    "typeIBunapplicable",
    "typeIIapplicable",
    "typeIIart29Applicable",
    "article5Applicable",
    "conditionsapplicable",
    "documentationsapplicable"
})
public class VariationItem {

    protected Integer selected;
    protected String title;
    protected String identifier;
    protected String shortName;
    protected Integer typeIA;
    protected Integer typeIAIN;
    protected Integer typeIB;
    protected Integer typeIBun;
    protected Integer typeII;
    protected Integer typeIIart29;
    @XmlElement(required = true)
    protected String typeVet;
    @XmlElement(name = "alternative-timetable", required = true)
    protected VariationItem.AlternativeTimetable alternativeTimetable;
    protected Integer article5;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    protected String comment;
    protected VariationItem.Conditions conditions;
    protected VariationItem.Documentations documentations;
    protected boolean typeIAapplicable;
    protected boolean typeIAINapplicable;
    protected boolean typeIBapplicable;
    protected boolean typeIBunapplicable;
    protected boolean typeIIapplicable;
    @XmlElement(name = "typeIIart29applicable")
    protected boolean typeIIart29Applicable;
    @XmlElement(name = "article5applicable")
    protected boolean article5Applicable;
    protected boolean conditionsapplicable;
    protected boolean documentationsapplicable;

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSelected(Integer value) {
        this.selected = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the typeIA property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeIA() {
        return typeIA;
    }

    /**
     * Sets the value of the typeIA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeIA(Integer value) {
        this.typeIA = value;
    }

    /**
     * Gets the value of the typeIAIN property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeIAIN() {
        return typeIAIN;
    }

    /**
     * Sets the value of the typeIAIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeIAIN(Integer value) {
        this.typeIAIN = value;
    }

    /**
     * Gets the value of the typeIB property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeIB() {
        return typeIB;
    }

    /**
     * Sets the value of the typeIB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeIB(Integer value) {
        this.typeIB = value;
    }

    /**
     * Gets the value of the typeIBun property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeIBun() {
        return typeIBun;
    }

    /**
     * Sets the value of the typeIBun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeIBun(Integer value) {
        this.typeIBun = value;
    }

    /**
     * Gets the value of the typeII property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeII() {
        return typeII;
    }

    /**
     * Sets the value of the typeII property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeII(Integer value) {
        this.typeII = value;
    }

    /**
     * Gets the value of the typeIIart29 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeIIart29() {
        return typeIIart29;
    }

    /**
     * Sets the value of the typeIIart29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeIIart29(Integer value) {
        this.typeIIart29 = value;
    }

    /**
     * Gets the value of the typeVet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeVet() {
        return typeVet;
    }

    /**
     * Sets the value of the typeVet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeVet(String value) {
        this.typeVet = value;
    }

    /**
     * Gets the value of the alternativeTimetable property.
     * 
     * @return
     *     possible object is
     *     {@link VariationItem.AlternativeTimetable }
     *     
     */
    public VariationItem.AlternativeTimetable getAlternativeTimetable() {
        return alternativeTimetable;
    }

    /**
     * Sets the value of the alternativeTimetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariationItem.AlternativeTimetable }
     *     
     */
    public void setAlternativeTimetable(VariationItem.AlternativeTimetable value) {
        this.alternativeTimetable = value;
    }

    /**
     * Gets the value of the article5 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getArticle5() {
        return article5;
    }

    /**
     * Sets the value of the article5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setArticle5(Integer value) {
        this.article5 = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link VariationItem.Conditions }
     *     
     */
    public VariationItem.Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariationItem.Conditions }
     *     
     */
    public void setConditions(VariationItem.Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the documentations property.
     * 
     * @return
     *     possible object is
     *     {@link VariationItem.Documentations }
     *     
     */
    public VariationItem.Documentations getDocumentations() {
        return documentations;
    }

    /**
     * Sets the value of the documentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariationItem.Documentations }
     *     
     */
    public void setDocumentations(VariationItem.Documentations value) {
        this.documentations = value;
    }

    /**
     * Gets the value of the typeIAapplicable property.
     * 
     */
    public boolean isTypeIAapplicable() {
        return typeIAapplicable;
    }

    /**
     * Sets the value of the typeIAapplicable property.
     * 
     */
    public void setTypeIAapplicable(boolean value) {
        this.typeIAapplicable = value;
    }

    /**
     * Gets the value of the typeIAINapplicable property.
     * 
     */
    public boolean isTypeIAINapplicable() {
        return typeIAINapplicable;
    }

    /**
     * Sets the value of the typeIAINapplicable property.
     * 
     */
    public void setTypeIAINapplicable(boolean value) {
        this.typeIAINapplicable = value;
    }

    /**
     * Gets the value of the typeIBapplicable property.
     * 
     */
    public boolean isTypeIBapplicable() {
        return typeIBapplicable;
    }

    /**
     * Sets the value of the typeIBapplicable property.
     * 
     */
    public void setTypeIBapplicable(boolean value) {
        this.typeIBapplicable = value;
    }

    /**
     * Gets the value of the typeIBunapplicable property.
     * 
     */
    public boolean isTypeIBunapplicable() {
        return typeIBunapplicable;
    }

    /**
     * Sets the value of the typeIBunapplicable property.
     * 
     */
    public void setTypeIBunapplicable(boolean value) {
        this.typeIBunapplicable = value;
    }

    /**
     * Gets the value of the typeIIapplicable property.
     * 
     */
    public boolean isTypeIIapplicable() {
        return typeIIapplicable;
    }

    /**
     * Sets the value of the typeIIapplicable property.
     * 
     */
    public void setTypeIIapplicable(boolean value) {
        this.typeIIapplicable = value;
    }

    /**
     * Gets the value of the typeIIart29Applicable property.
     * 
     */
    public boolean isTypeIIart29Applicable() {
        return typeIIart29Applicable;
    }

    /**
     * Sets the value of the typeIIart29Applicable property.
     * 
     */
    public void setTypeIIart29Applicable(boolean value) {
        this.typeIIart29Applicable = value;
    }

    /**
     * Gets the value of the article5Applicable property.
     * 
     */
    public boolean isArticle5Applicable() {
        return article5Applicable;
    }

    /**
     * Sets the value of the article5Applicable property.
     * 
     */
    public void setArticle5Applicable(boolean value) {
        this.article5Applicable = value;
    }

    /**
     * Gets the value of the conditionsapplicable property.
     * 
     */
    public boolean isConditionsapplicable() {
        return conditionsapplicable;
    }

    /**
     * Sets the value of the conditionsapplicable property.
     * 
     */
    public void setConditionsapplicable(boolean value) {
        this.conditionsapplicable = value;
    }

    /**
     * Gets the value of the documentationsapplicable property.
     * 
     */
    public boolean isDocumentationsapplicable() {
        return documentationsapplicable;
    }

    /**
     * Sets the value of the documentationsapplicable property.
     * 
     */
    public void setDocumentationsapplicable(boolean value) {
        this.documentationsapplicable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="alternative-timetable-rb" type="{http://www.ema.eaf/dictionary/}radiobutton"/>
     *         &lt;element name="confirm-alternative-timetable-cb" type="{http://www.ema.eaf/dictionary/}yes-no"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alternativeTimetableRb",
        "confirmAlternativeTimetableCb"
    })
    public static class AlternativeTimetable {

        @XmlElement(name = "alternative-timetable-rb", required = true)
        protected BigInteger alternativeTimetableRb;
        @XmlElement(name = "confirm-alternative-timetable-cb")
        protected int confirmAlternativeTimetableCb;

        /**
         * Gets the value of the alternativeTimetableRb property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAlternativeTimetableRb() {
            return alternativeTimetableRb;
        }

        /**
         * Sets the value of the alternativeTimetableRb property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAlternativeTimetableRb(BigInteger value) {
            this.alternativeTimetableRb = value;
        }

        /**
         * Gets the value of the confirmAlternativeTimetableCb property.
         * 
         */
        public int getConfirmAlternativeTimetableCb() {
            return confirmAlternativeTimetableCb;
        }

        /**
         * Sets the value of the confirmAlternativeTimetableCb property.
         * 
         */
        public void setConfirmAlternativeTimetableCb(int value) {
            this.confirmAlternativeTimetableCb = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="condition" type="{http://www.ema.eaf/dictionary/}condition" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "condition"
    })
    public static class Conditions {

        @XmlElement(required = true)
        protected List<Condition> condition;

        /**
         * Gets the value of the condition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the condition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCondition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Condition }
         * 
         * 
         */
        public List<Condition> getCondition() {
            if (condition == null) {
                condition = new ArrayList<Condition>();
            }
            return this.condition;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="documentation" type="{http://www.ema.eaf/dictionary/}documentation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentation"
    })
    public static class Documentations {

        @XmlElement(required = true)
        protected List<Documentation> documentation;

        /**
         * Gets the value of the documentation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Documentation }
         * 
         * 
         */
        public List<Documentation> getDocumentation() {
            if (documentation == null) {
                documentation = new ArrayList<Documentation>();
            }
            return this.documentation;
        }

    }

}
