export enum DirectorateCode {
  CLASSIFIER_REGISTER_FOOD_CONTROL_DIRECTORATE_CODE = '0002001',
  CLASSIFIER_REGISTER_PLANT_PROTECTION_PRODUCT_DIRECTORATE_CODE = '0002002',
  CLASSIFIER_REGISTER_PHYTOSANITARY_CONTROL_DIRECTORATE_CODE = '0002003',
}
