logging:
  level:
    org.springframework:
      boot.autoconfigure: ERROR
      security: DEBUG
      web: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE
    com.zaxxer.hikari: DEBUG
    reactor.netty.http.client: DEBUG
    bg.bulsi.bfsa: DEBUG
