spring:
  datasource:
    url: 'jdbc:postgresql://172.23.240.5:5432/bfsa' #?currentSchema=bfsa'
    username: bulsiadmin
    password: bulsivirtual-bfsa
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2dll:
          create_namespaces: true
