version: "3"
services:
  bfsa:
    container_name: bfsa-be
    image: bfsa-be:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/srv/bfsa-be/logs:/home/bfsa/logs"
      - "/home/srv/bfsa-be/storage:/home/bfsa/storage"
    networks:
      - net-bfsa
    ports:
      - "80:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILES_SPRING}"
networks:
  net-bfsa:
    driver: bridge