### POST login (Set access_token to the global variables)
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=expert_ppp&password=expert_ppp

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  ApplicationS2274Controller # get by record id
GET {{host}}/api/s2274-applications/2552
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


### ApplicationS2274Controller # approve
PUT {{host}}/api/s2274-applications/2352/approve
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS2274Controller # refuse
PUT {{host}}/api/s2274-applications/2352/refuse
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ApplicationS2274Controller # forCorrection
PUT {{host}}/api/s2274-applications/502/for-correction
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "id": "502",
  "description": "Съпбщение с причина за връщане за корекция."
}
