### POST login (Set access_token to the global variables)
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=expert&password=expert

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}

###  ApplicationS3181Controller # register
POST {{host}}/api/s3181-applications/register
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "requestorIdentifier": "01210s2000000",
  "requestorFullName": "RequestorFullName0",
  "requestorPhone": "123456789",
  "requestorEmail": "requ7771s2estor31800@mail.com",
  "requestorPowerAttorneyNumber": "123132132",
  "requestorPowerAttorneyNotary": "13132123",
  "requestorPowerAttorneyDate": "2023-08-09",
  "requestorPowerAttorneyUntilDate": "2023-08-09",
  "requestorAuthorTypeCode": "01301",
  "applicantIdentifier": "3233s77133333",
  "applicantFullName": "Applicant3FullName5",
  "applicantEmail": "app7712licants35@mail.com",
  "applicantPhone": "2134324",
  "applicantLegalForm": "string",
  "applicantHeadOfficeSettlementCode": "02676",
  "applicantHeadOfficeAddress": {
    "address": "Head office address",
    "postCode": "1000",
    "addressTypeCode": "00201",
    "settlementCode": "02676"
  },
  "applicantCorrespondenceAddress": {
    "address": "Correspondence address",
    "postCode": "1000",
    "addressTypeCode": "00203",
    "settlementCode": "02676"
  },
  "branchSequenceNumber": "01",
  "recordId": "string",
  "recordIdentifier": "string",
  "serviceType": "S3181",
  "regNumber": "string",
  "regDate": "2023-08-10",
  "price": 0,
  "recordStatus": "ENTERED",
  "approvalDocumentStatus": "ENTERED",
  "address": {
    "settlementCode": "02676",
    "address": "Base Address",
    "phone": "010101010",
    "mail": "basemail@mail.com",
    "url": "222.string.com"
  },
  "contractorType": "PHYSICAL",
  "facilityZone": "string",
  "facilityMunicipality": "string",
  "facilitiesPaperNumbers": [],
  "vehicleBOS": [
    {
      "vehicleOwnershipType": "01503",
      "vehicleType": "01504",
      "vehicleBrandModel": "МЕРЦЕДЕС СПРИНТЕР",
      "vehicleRegistrationPlate": "Е 00 33 ВС"
    }
  ],
  "commencementActivityDate": "2024-09-30T15:30+01:00"
}


###  ApplicationS3181Controller # getApplicationS3181 by record id
GET {{host}}/api/s3181-applications/37fe24dc-bcdd-4b90-a34e-fea95373f302
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS3181Controller # approveApplicationS3181
PUT {{host}}/api/s3181-applications/33acf499-cecd-44fd-a261-bf5974207e3f/approve
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS3181Controller # refuseApplicationS3181
PUT {{host}}/api/s3181-applications/676317d6-3d5f-4237-b483-934344d32fc0/refuse
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ApplicationS3181Controller # forCorrectionApplicationS3181
PUT {{host}}/api/s3181-applications/77fee257-715e-4fcb-a6e3-55977efa713b/for-correction
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "id": "77fee257-715e-4fcb-a6e3-55977efa713b",
  "description": "За корекция, поради нвалиден адрес за коренспонденция."
}