### POST login (Set access_token to the global variables)
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  ApplicationS2697Controller # getApplicationS2697 by record id
GET {{host}}/api/s2697-applications/404
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS2697Controller # approveApplicationS2697
PUT {{host}}/api/s2697-applications/602/approve
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS2697Controller # refuseApplicationS2697
PUT {{host}}/api/s2697-applications/676317d6-3d5f-4237-b483-934344d32fc0/refuse
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ApplicationS2697Controller # forCorrectionApplicationS2697
PUT {{host}}/api/s2697-applications/77fee257-715e-4fcb-a6e3-55977efa713b/for-correction
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "id": "77fee257-715e-4fcb-a6e3-55977efa713b",
  "description": "За корекция, поради нвалиден адрес за коренспонденция."
}