### POST login (Set access_token to the global variables)
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=expert_food&password=expert_food

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


### ApplicationS7693Controller # getApplicationS7693 by record id
GET {{host}}/api/s7693-applications/2402
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS7693Controller # approveApplicationS7693
PUT {{host}}/api/s7693-applications/{record-id}/approve
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS7693Controller # refuseApplicationS7693
PUT {{host}}/api/s7693-applications/{record-id}/refuse
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ApplicationS7693Controller # forCorrectionApplicationS7693
PUT {{host}}/api/s7693-applications/{record-id}/for-correction
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "id": "77fee257-715e-4fcb-a6e3-55977efa713b",
  "description": "За корекция, поради нвалиден адрес за коренспонденция."
}