### POST login (Set access_token to the global variables)
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=expert_food_ho&password=expert_food_ho

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  ApplicationS2698Controller # getApplicationS2698 by record id
GET {{host}}/api/s2698-applications/1502
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ApplicationS2698Controller # approveApplicationS2698
PUT {{host}}/api/s2698-applications/2352/approve
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "recordId": "2352",
  "orderNumber": "1"
}

###  ApplicationS2698Controller # refuseApplicationS2698
PUT {{host}}/api/s2698-applications/752/refuse
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ApplicationS2698Controller # forCorrectionApplicationS2698
PUT {{host}}/api/s2698-applications/752/for-correction
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "id": "752",
  "description": "За корекция, поради нвалиден адрес за коренспонденция."
}