### POST login (Set access_token to the global variables)
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=expert_food&password=expert_food

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  DocumentsController # export paper
GET {{host}}/api/documents/2402/export-paper
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  DocumentsController # export order
GET {{host}}/api/documents/2152/export-order
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg
